### ISSUE TITLE
Modals Input Field Padding

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Frontend#1002]
This has definitely lower priority, while working on mocks I realized it was a bit strange that the input fields have a small left padding in our modals.

<img width="544" alt="input field" src="https://user-images.githubusercontent.com/28826387/203311079-becc1a7a-14c7-43ca-a305-92f613569de7.png">

Seems like Github is not doing that in their registration
<img width="298" alt="modals" src="https://user-images.githubusercontent.com/28826387/203311093-09ec01bc-8b0b-499d-b4d1-e9c93744fb4e.png">

Did anyone fine any other reference on Github that indicates input field should have a left padding?

**Comment by ArcAnya** [comment]
Agreed @rickkdev  
Asssigned myself but actually @Seb887 is doing this

**Comment by seb887** [comment]
Working on it @ArcAnya

**Comment by seb887** [comment]
I have a suggestion: I find it easier to read if the headings are in semi-bold

![image](https://user-images.githubusercontent.com/85454566/204057707-7c91328d-0257-464b-a0ed-7472d79d6054.png)

**Comment by ArcAnya** [comment]
I think it looks good and seems aligned with Github guidelines: go for it 👍 

In general, we follow these github guidelines: https://primer.style/
