### ISSUE TITLE
Wrong network not showing up - staging

### ISSUE THREAD

**Issue by Christopher-Stevers** [OpenQDev/OpenQ-Frontend#1010]

**Comment by ArcAnya** [comment]
Do you mean the missing that the button does not transform into "use Polygon Network" on Claim, Funding (and probably refund)?
I'll do that - otherwise not sure what you meant

![image](https://user-images.githubusercontent.com/75732239/203930177-b2d291fc-41ea-4495-b2f0-f549cf85cf9e.png)

**Comment by ArcAnya** [comment]
Actually - I believe I was able to reproduce the issue (i.e. when changing network, the condition isOnCorrectNetwork would be wrong sometimes) and on local it seemed to work fine with the following commit: https://github.com/OpenQDev/OpenQ-Frontend/pull/1012/commits/ec18e889b40b5535748ff8a84e05dde5b704d9e8

Let me know if that was the issue you were referring to.
