### ISSUE TITLE
Only show Connect Wallet button if authenticated with github

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1024]
Right now, we show Wallet Connect by default.

Let's mirror the login behavior of Gitcoin, in which we will only show Wallet Connect if the user is signed in with Github.

NOTE: I know we discussed what an email client might look like - for now this can be built out just with Github. Email will come thereafter

**Comment by ArcAnya** [comment]
Hope to have made our future changes related to the User login flow easier with #1025
