### ISSUE TITLE
Hoist the LoginModal out of ConnectButton; make it dynamically display based on auth state

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1058]
Right now the LoginModal display logic is contained within ConnectButton.

I think it would be best if LoginModal were a "presentational component", and on each page (or at some place higher) is displayed or not according to the results of `useAuth`

**HOOKS AND COMPONENT RE-RENDERS**

In general, we don't want useAuth() to be running in components. It should run ONCE at the highest level `[page].js` and the result set on the AuthState context.

This will re-render all components below it that use the auth context.

Otherwise, we are going to be HAMMERING the auth api with `checkAuth` on every component re-render.

**Comment by ArcAnya** [comment]
Guess it was already partly implemented with the last changes - guess the "Log in" button going to simple LoginModal vs. "Sign up" going to the actual page..?
