### ISSUE TITLE
Graceful 404 for non-existent users

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1059]
Let's fail gracefully on user pages

Here's one with a VALID MongoDB id. that fails loudly

And one with a random id. That shows unexpected error

<img width="1532" alt="Screenshot 2022-12-10 at 1 18 57 PM" src="https://user-images.githubusercontent.com/93455288/206871817-19f79c55-0336-42fb-a6e1-ff46d8025940.png">
<img width="1399" alt="Screenshot 2022-12-10 at 1 19 11 PM" src="https://user-images.githubusercontent.com/93455288/206871819-aca9ad8e-8122-430c-9f34-62864b1cf4e7.png">

**Comment by ArcAnya** [comment]
Seems like the first type of error was already caught by latest changes in the hackathon branch - for the second, it was showing an empty user with the OpenQ logo so now it shows the UnexpectedErrorModal instead when the user has no email or github (cd PR #1068).
