### ISSUE TITLE
Where does org invoicing details show up?

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1062]
I'm confused about why I see Org invoicing on my user account.

What's the logic here?

It doesn't update anything on my User when i update it

<img width="873" alt="Screenshot 2022-12-10 at 1 29 01 PM" src="https://user-images.githubusercontent.com/93455288/206872172-6dd96927-66ff-4844-ae62-2c51c654d160.png">

**Comment by Christopher-Stevers** [comment]
It should update fields in your user, then once these are updated they can be used invoicing.

**Comment by Christopher-Stevers** [comment]
Those details might be coming from you having entered them in the invoicing freelancer tab.
