### ISSUE TITLE
Invoicing Organization Flow

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Frontend#1073]
For Invoicing we will have an additional collapsable menu in the funding sub-page.

![Group 1 (1)](https://user-images.githubusercontent.com/28826387/207308103-c9d65cb8-943e-4686-a1f8-9be06bda996c.png)
![Group 2](https://user-images.githubusercontent.com/28826387/207308742-459c1a67-0843-4814-8e03-d83ed0fdfac2.png)

- [x] This will only appear in  contracts that have invoicing activated
- [x] If the user already has on his profile page invoicing details entered we autofill the fields for him, with the option to adjust them
- [x] If a user continues to fund the bounty, we check if all the information that is required was filled out (we only open the collapsable menu automatically for him if something is missing)
- [x] We highlight the missing fields in red and tell him at the top as a notification what is missing (the same should happen in the developer invoicing flow)

If the user already had information in this profile and he adjusted it in the funding process:
- [x] We ask the user if he wants to use the edited information as the main invoicing details

If the user didn't have any information about invoicing 
- [x] We automatically store the details on his profile page

If the user is using the same invoicing details
- [x] Nothing happens we just continue with the transaction

**Comment by rickkdev** [comment]
We should probably also have the information somewhere that this contract requires invoicing data, but maybe that is also redundant.

**Comment by Christopher-Stevers** [comment]
>We ask the user if he wants to use the edited information as the main invoicing details

@rickkdev do to our architecture the user should always be updating his main invoicing details, otherwise we need to store temporary invoicing details that are only required for a single deposit. In this context that would mean that the user would only would always be updating his main invoicing details in the dropdown. If you want we can make them confirm that they'd like to update the invoicing details for the logged in users.

**Comment by rickkdev** [comment]
Okay then lets forget that and just update it

> > We ask the user if he wants to use the edited information as the main invoicing details
> 
> @rickkdev do to our architecture the user should always be updating his main invoicing details, otherwise we need to store temporary invoicing details that are only required for a single deposit. In this context that would mean that the user would only would always be updating his main invoicing details in the dropdown. If you want we can make them confirm that they'd like to update the invoicing details for the logged in users.

Okay then lets forget that and just update it
