### ISSUE TITLE
[STAGING] Unexpected error showing after minting a fixed contract

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#1084]
Minted a fixed contract with no invoicing and budget of 0.01 USDC. It shows the error BUT the contract actually minted successfully.

![image](https://user-images.githubusercontent.com/75732239/207853148-408f083a-8d10-41cf-b044-d0d5d33bba53.png)

**Comment by Christopher-Stevers** [comment]
Looks to be working on staging at this point - perhaps it was an issue with github not being authenticated.

**Comment by ArcAnya** [comment]
Tbh it happens every now and then when minting on staging - it's been like that for at least 1-2 months, error keeps showing but not on a deterministic pattern

**Comment by Christopher-Stevers** [comment]
Oh, interesting.

**Comment by FlacoJones** [comment]
Closing because duplicate of https://github.com/OpenQDev/OpenQ-Frontend/issues/1093
