### ISSUE TITLE
[STAGING] Do we still need the commenting on simple contest contracts?

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#1087]
On Admin Tab => there is still the commenting indication, but I guess that is irrelevant now for contests since they'd work with the Submissions tab?

![image](https://user-images.githubusercontent.com/75732239/207858695-0794af50-38ff-439c-ac61-475c28629299.png)

**Comment by FlacoJones** [comment]
We do not. NUKE THEM!
