### ISSUE TITLE
[STAGING] make sure dates are reasonable

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#1089]
Currently I manage to successfully deploy a hackathon enabled contest contract with dates in the past:
Make sure to check that: date 1 and 2 are in the future && date 2 > date 1

![image](https://user-images.githubusercontent.com/75732239/207862081-32b0f629-1c5d-4de1-bfb9-fd062cfd9ce2.png)
![image](https://user-images.githubusercontent.com/75732239/207862521-847ec613-5235-442b-a010-367aba2247e0.png)

**Comment by Christopher-Stevers** [comment]
@alo9507  should we just hide the enable hackathon registration section? I think we are still are waiting on mocks/UX for all of this.

**Comment by FlacoJones** [comment]
Add a method in Utils.js to validate dates - probably some nice built-ins in JS already?
