### ISSUE TITLE
[STAGING] Does not display token & values on deposits

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#1090]
![image](https://user-images.githubusercontent.com/75732239/207884596-460306b5-5d19-47b4-b263-3dba4794aa89.png)

**Comment by Christopher-Stevers** [comment]
![image](https://user-images.githubusercontent.com/72156679/207912643-e7b91224-6c2a-4a33-a474-cad2b2073016.png)
Not able to reproduce.

**Comment by ArcAnya** [comment]
It's back on for me to now
