### ISSUE TITLE
[PROD] Sorting issues per date ('newest') seems broken

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#1099]
![image](https://user-images.githubusercontent.com/75732239/208129778-4c885205-b135-4fc3-9759-15164b18a39f.png)

**Comment by Christopher-Stevers** [comment]
Was the production db of bounties dropped at some point? It seems like the mint time and the created time in the db are out of sync. For example, the bounty with address: "0x0310F16eE87824DeC25D25ec91996c5EB0f83050" seems to have a mint time and a bountyCreated time  (the time coming from the db that says when the bounty was created) that are 5 days apart.  Might be something for Andrew to take a look at.

**Comment by Christopher-Stevers** [comment]
Any ideas what might be up with this @alo9507 ?

**Comment by FlacoJones** [comment]
https://github.com/OpenQDev/OpenQ-Token-Price-Cron-Job/issues/28
