### ISSUE TITLE
KYC Integration

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Frontend#1105]
Docs: https://main.docs.pre.kycdao.xyz/buidl/sdks/uisdk/with_react/

Example code: https://gist.github.com/PAStheLoD/0bdc1988563fa0876a72b9d134405fc5

Start here to learn how it will look like:
https://main.docs.pre.kycdao.xyz/integration-examples/evm-no-react/

Lets go ;)

**Comment by ArcAnya** [comment]
So far experiencing issues with the module import - paired on it with @Christopher-Stevers, but it seemed like we'd have to go down the rabbit hole - hence posted in their discord and will try to find a solution there.
