### ISSUE TITLE
Sum for Tiered is somehow still going above 100%

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1112]
I found a glitch where I can still pull the tab to be above 100%

<img width="666" alt="Screenshot 2022-12-19 at 7 38 33 PM" src="https://user-images.githubusercontent.com/93455288/208554786-3769c70b-19dd-46c8-893a-d37c1965f918.png">

**Comment by ArcAnya** [comment]
I believe it's a glitch in the Matrix. Had a look - it only behaves like that with precisely these number (39% and 32%) - but they could be in any other constellation - they unlock magical FE powers.
