### ISSUE TITLE
Create Contract Modal: Add alternative contract logo from different org 

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Frontend#1115]
## About
Orgs could collab with contests together and would create bounties in repositories that are not theirs.

### What to do?
In this case we should offer a checkbox that allows using the logo of their organization for this bounty (which will be displayed in the bounty card and in the modal).

We should probably offer this feature also for Fixed-Price & Split-Price Bounties.

### How it will look like

(under set a budget)

Show a different Organisation
Enter an organization's GitHub link to display an alternative logo on this contract.
[input]

**Comment by ArcAnya** [comment]
Remember this as being part of the broader discussion about the new Organization Management way - is it related to any of the work you've done @Christopher-Stevers, or can it simply be taken on separately?
