### ISSUE TITLE
/__tests__/Admin/Users.test.js

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1120]
Rewrite this render test using a snapshot test rather than codebased renders statements

**Comment by ArcAnya** [comment]
https://codeburst.io/using-tomatchsnapshot-with-react-hooks-72b639ec75

https://www.ksharifbd.com/blog/testing-react-custom-hook-how-to-mock-usecontext-value-with-jest/

https://polvara.me/posts/mocking-context-with-react-testing-library



https://levelup.gitconnected.com/unit-testing-for-react-with-jest-snapshots-ae3e6f58fe07

https://chanonroy.medium.com/mocking-hooks-for-testing-with-jest-and-react-testing-library-d34505616d12
