### ISSUE TITLE
Assignees Image Icon is funky

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Frontend#1206]
https://app.openq.dev/contract/I_kwDOIvxvu85a9Y-X/0xa4cd74e1561102eb03d073ce4130fdb57f5f9ba5

Not aligned with name:

![mkt](https://user-images.githubusercontent.com/28826387/213148897-f82ddd03-158d-4fcc-925c-398ff5e883d0.png)

**Comment by ArcAnya** [comment]
already corrected with #1147 in #1196
