### ISSUE TITLE
Responsive login page 

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Frontend#1212]
# Details

**Responsiveness**

![Login](https://user-images.githubusercontent.com/28826387/213432740-a099608c-d462-487c-a027-7961a1923e6e.png)

We need a responsive landing page, create some cool stable diffusion login page images with similar prompts (here is the original one):

`science fiction anime majestic alchemist night sky with planets and galaxies, two point perspective, high details, masterpiece, trending on artstation, hyper-detailed, by vincent di fate and joe fenton, two point perspective, bold line art, like a oil painting of the construction of a unified theory, surrealism, surreal concept art, lifelike, photorealistic, digital painting, aesthetic, smooth, sharp focus, artstation hd, by greg rutkowski, bruce pennington, valentina remenar and asher duran,`

**Comment by aimun-naharr** [comment]
I want to work on it. Can you describe it a little more?

**Comment by ManyRios** [comment]
I'm ready to work on this. I already have all the dependencies installed
