### ISSUE TITLE
magic link login bug

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Frontend#1213]
## Bug fix

I think magic link is down, I can't log in. When I enter my email and click login nothing happens, also seems like no relevant console message.

**Comment by Christopher-Stevers** [comment]
Looks like its fixed locally, waiting to be able to do a successful staging release.

**Comment by Christopher-Stevers** [comment]
Still having issues with this. Not sure if its an issue on our end or theirs. I find that login fails if I try to log in after logging out, and won't work until I clear cookies and reload.
