### ISSUE TITLE
Message for Graph Indexing looks weird

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#1227]
Remove the symbol that seems to be in the middle of the message

![image](https://user-images.githubusercontent.com/75732239/214233431-6f0faf71-fc28-4bcd-91ef-00e3545ea033.png)

**Comment by Sheikh-JamirAlam** [comment]
I would like to work on this issue. But I have been facing an issue. I was able to run the Local Json Server. But when I try to run the app, I face this.

![image](https://user-images.githubusercontent.com/48979376/214339618-0a8734bc-5014-4405-b6d8-2deec5094f83.png)

**Comment by Christopher-Stevers** [comment]
Hi @Sheikh-JamirAlam  I've run into similar issues running it on windows. if you delete the DEPLOY_ENV="staging" on line 12 of the package.json  and add it to your .env file you should be able to get it running.

N.B. not all areas of the app are accessible on the targeting-staging boot, so to replicate the issue I'd recommend going to 
http://localhost:3000/contract/I_kwDOGWnnz85ayL5c/0x39c5a3623fa093809c128b2822658459ff8f00db, then messing around with the props being passed to BountyCardDetails or ActionBubble until you can replicate it.
 Let me know if you have any other issues!

**Comment by Sheikh-JamirAlam** [comment]
@Christopher-Stevers Thanks for informing. Just, if I delete the DEPLOY_ENV="staging", what command should I use to deloy?

**Comment by Christopher-Stevers** [comment]
@Sheikh-JamirAlam  you won't need to add a command, just add it to the .env file.
