### ISSUE TITLE
Something to indicate when Invoicing info is already completed

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1284]
Completed, not Sent

<img width="642" alt="Screenshot 2023-02-06 at 11 34 39 AM" src="https://user-images.githubusercontent.com/93455288/217043710-3eca253a-11d2-4aa2-8792-cd16d5a772f1.png">

**Comment by ArcAnya** [comment]
I think this one is related to #1268 @Christopher-Stevers ?
