### ISSUE TITLE
Unable to close KYC modal, while txn pending and even after Rejecting in MetaMask

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1311]
<img width="1423" alt="Screenshot 2023-02-11 at 11 46 15 AM" src="https://user-images.githubusercontent.com/93455288/218273021-b51d7cf7-5731-434f-9590-03910c3228e9.png">

**Comment by ArcAnya** [comment]
Already reported to the KycDAO team - waiting for fixes - related to #1253

**Comment by ArcAnya** [comment]
Actually fixed in #1325 => adding a connect button to prevent user to trigger the widget when on wrong Network or when no wallet connected
