### ISSUE TITLE
Loading screen for Issues and Organizations

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#132]
When issues are loading right now, we show nothing.

We'd like to do something similar to balancer, linkedin, snapshot etc, which is having a gradient animated placeholder where the bounty cards or organization cards should be.

You can't see it here, but the below is animated

<img width="1646" alt="Screen Shot 2022-03-15 at 12 43 15 PM" src="https://user-images.githubusercontent.com/93455288/158439229-60e0871f-092b-4920-8e54-cd58b4f5f020.png">

**Comment by FlacoJones** [comment]
So for the bounty cards for example, the loading element should be the shape of the bounty cards.

For the organization cards, the loading element should be the shape of the organization cards.

It might make sense to find a generalized approach to this that can just be resized in all these different contexts.

It doesn't seem that Tailwind offers this component, so we'll need to bring it in from some other library.

Post suggestions here and we'll decide on one

**Comment by Christopher-Stevers** [comment]
Took a look at this one and it looks like it might be what we are looking for [react-loading-skeleton]( https://www.npmjs.com/package/react-loading-skeleton) . It basically provides a skeleton loader that is auto-sized by default, and it looks like it is somewhat actively maintained.
