### ISSUE TITLE
[Staging] "avatar url" showing on small bounty card

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#1326]
Most probably needs a placeholder (or sthg else / nothing)  when there is no avatar url for the alternative org?

![image](https://user-images.githubusercontent.com/75732239/218450641-b197b5ca-b0b1-463b-8ae0-7f871ce3c587.png)

**Comment by ArcAnya** [comment]
Can't reproduce the avatarUrl glitch as normally there is always a default image on github
Need to know which link was used for the alternative org to fix

**Comment by Christopher-Stevers** [comment]
@ArcAnya its what happens when the contract is directly called with alternative an invalid avatar url.
https://dev.to/elisabethleonhardt/configure-fallback-images-in-react-and-nextjs-54ej this details what you can do in that case
