### ISSUE TITLE
Do we want to lock the token choice once first deposit made on Fixed Contest?

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#1334]
We had done this for Split Contracts to protect the funders in the FE from setting a different token once a first deposit has been made - I believe it makes sense in the fixed contest as well 
Related to #1304 => tokens in fundpage & admin are now preset to either deposit token or payoutschedule token for fixed contests.

**Comment by Christopher-Stevers** [comment]
yeah, I think this makes sense
