### ISSUE TITLE
Add a little check on the tab of KYC + Invoicing info if complete

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1342]

**Comment by Christopher-Stevers** [comment]
I thought we were already doing this.

**Comment by Christopher-Stevers** [comment]
![image](https://user-images.githubusercontent.com/72156679/219711848-ef9134d5-0b45-4ebc-bb98-70b992b8f6fb.png)
Is this the kind of thing you were looking for here?
