### ISSUE TITLE
Console warnings 

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1353]
<img width="1679" alt="Screenshot 2023-02-15 at 3 21 44 PM" src="https://user-images.githubusercontent.com/93455288/219169666-294bff70-b338-4f78-83b6-8d3d2f1dee37.png">

**Comment by FlacoJones** [comment]
<img width="1680" alt="Screenshot 2023-02-15 at 3 23 18 PM" src="https://user-images.githubusercontent.com/93455288/219170149-d0008892-27cd-45d0-bdae-e43b6ae58ce7.png">

Two of the above are related to height/width of images

**Comment by ArcAnya** [comment]
Seems to be a known bug from next/image https://github.com/vercel/next.js/issues/40762
