### ISSUE TITLE
possible issue - request page looks like its showing the email of participants

### ISSUE THREAD

**Issue by Christopher-Stevers** [OpenQDev/OpenQ-Frontend#1361]
Make sure we aren't pulling private user data from the contestants here to show the email - if we are it won't work when the requester isn't the person looking at this page.
![image](https://user-images.githubusercontent.com/72156679/219344001-73992690-28ee-4304-a77c-cc16e7c254dc.png)

**Comment by Christopher-Stevers** [comment]
waiting for confirmation of graphql schema

**Comment by FlacoJones** [comment]
Being discussed in an internal-dev thread
