### ISSUE TITLE
z-index on new landing page

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1370]
<img width="1073" alt="Screenshot 2023-02-16 at 1 39 51 PM" src="https://user-images.githubusercontent.com/93455288/219469888-e43d23ed-eba5-4a8d-baef-f8bb8ed1df38.png">

**Comment by mktcode** [comment]
Fixed it by adjusting my z-indexes. A more robust way of handling modals and similar overlays is to [teleport the component](https://betterprogramming.pub/what-is-react-teleportation-7d9c5f6eacee) to outside of the rest of the app. cc: @rickkdev
