### ISSUE TITLE
Staging: contest contracts not showing under /contests

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#1390]
Not sure if I'm missing sthg here (maybe with our new difference between contests and hackathons) - but when creating "fixed contests" on staging, they don't appear under "all issues" in the "/contests" page:

![image](https://user-images.githubusercontent.com/75732239/220113346-fabbcfec-9fa9-40ec-9a26-a1d5eb2f2c0c.png)

**Comment by Christopher-Stevers** [comment]
I can take this, one I think its something to do with changing language from contests to hackathons.

**Comment by ArcAnya** [comment]
Awesome, thx
