### ISSUE TITLE
Confusing signature

### ISSUE THREAD

**Issue by Christopher-Stevers** [OpenQDev/OpenQ-Frontend#1394]
![image](https://user-images.githubusercontent.com/72156679/220116059-1ff4a89c-574c-4adc-850d-3880904eddc5.png)
https://discord.com/channels/784862355804258304/971071700571672638/1077206849465622598

**Comment by Christopher-Stevers** [comment]
@alo9507  thoughts?

**Comment by FlacoJones** [comment]
It's paid for by OpenQ in our oracle

and yes we should add a date to this - nonce management would be even better, but harder to implement on the backend

@Christopher-Stevers what could be done here, is adding a serialized date (like a date that is produced exactly the same on the FE and the API) and then in the authorization check in the API, we would produce the SAME EXACT date, see that the signed date is the same, and then proceed IF AND ONLY IF IT IS

**Comment by FlacoJones** [comment]
doing this based on the date rather than a nonce is like the "poor man's approach" to adding an expiration date to a signed message - that way there a signed `OpenQ` message from yesterday can't be replayed today

**Comment by FlacoJones** [comment]
Will be solved by and Related to #1406
