### ISSUE TITLE
Improve claim UX

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#1398]
![image](https://user-images.githubusercontent.com/75732239/220123942-10cbd8ad-dc57-4d60-8ed9-ec37cdc1cd56.png)

**Comment by FlacoJones** [comment]
I agree - there should be great fanfare to claiming - bring back the confetti!!!

**Comment by rickkdev** [comment]
yeah we should also add a CTA (call to action) like signup to our newsletter - we know every hackathon in web3 and send you reminders etc and other stuff we want them to do - like redirect them to something we want them to read like a blog article

**Comment by Christopher-Stevers** [comment]
@ArcAnya let me know if you want me to pick this up.
