### ISSUE TITLE
Batch preview not working

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1404]
With this CSV:

[EthDenverBounties - Sheet1.csv](https://github.com/OpenQDev/OpenQ-Frontend/files/10787974/EthDenverBounties.-.Sheet1.csv)

I get the following output:

![Screenshot 2023-02-20 at 3 49 11 PM](https://user-images.githubusercontent.com/93455288/220203446-0c178126-e8f4-485c-b63c-ac5d0eec1ccb.png)

And this error in the console:

![Screenshot 2023-02-20 at 3 49 00 PM](https://user-images.githubusercontent.com/93455288/220203444-0de9b4e6-d443-46f7-999d-641b6115c41f.png)

**Comment by FlacoJones** [comment]
Update: it was caused by `getToken` not finding the example CSV's token

After setting it to the Chainlink token address, the new error is:

The number 1000 is not translating well

![Screenshot 2023-02-20 at 4 24 25 PM](https://user-images.githubusercontent.com/93455288/220206996-dbef3f6e-8021-4b39-87f3-8654b7cfe087.png)

**Comment by ArcAnya** [comment]
I see a different error:
![image](https://user-images.githubusercontent.com/75732239/220308371-52c10d9c-5305-4001-97bc-b3ad44fe8d8d.png)
![image](https://user-images.githubusercontent.com/75732239/220308459-ad6a1216-ca76-41f0-abbc-8476a4b5b3f5.png)
![image](https://user-images.githubusercontent.com/75732239/220308430-cab62728-a5e7-4172-91a6-3fc204177400.png)

**Comment by ArcAnya** [comment]
is related to the updates on CoinAPI performed yesterday:

https://github.com/OpenQDev/OpenQ-CoinAPI/issues/37

**Comment by ArcAnya** [comment]
is related to the updates on CoinAPI performed yesterday - reverting solves the issue

https://github.com/OpenQDev/OpenQ-CoinAPI/issues/37


![image](https://user-images.githubusercontent.com/75732239/220319465-9ffcb0a3-4239-40ac-ac53-cc48b01a1150.png)
