### ISSUE TITLE
Current Target Budget says zero on newly minted DERC20 contract

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1409]
Should this just be the sum of the tiers?

![Screenshot 2023-02-20 at 8 17 55 PM](https://user-images.githubusercontent.com/93455288/220230863-a922fdcf-60a9-4cb0-9475-8dbe61cf93cf.png)

**Comment by ArcAnya** [comment]
seems related to #1404

**Comment by ArcAnya** [comment]
is related to the updates on CoinAPI performed yesterday - reverting solves the issue

https://github.com/OpenQDev/OpenQ-CoinAPI/issues/37

![image](https://user-images.githubusercontent.com/75732239/220319576-9bec8c5e-a6e3-435f-ab2d-2be42aaa7447.png)
