### ISSUE TITLE
Current volumes incorrect on Admin page for DERC20 hackathon

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1410]
See `Current Payout Schedule` compared to the preview amounts shown in `Set Payout Schedule`

![Screenshot 2023-02-20 at 8 20 54 PM](https://user-images.githubusercontent.com/93455288/220231252-c9af24ec-f6f2-444a-8052-efa97269dabb.png)

**Comment by ArcAnya** [comment]
is related to the updates on CoinAPI performed yesterday - reverting solves the issue (values are defaulting to "1" when no value provided)

https://github.com/OpenQDev/OpenQ-CoinAPI/issues/37

![image](https://user-images.githubusercontent.com/75732239/220319716-7e962c1c-86b9-4a1c-85af-0ea4fcb2dc73.png)
