### ISSUE TITLE
On local, newly created bounties not appearing in Bounty List

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1411]
This may just be me, but I minted two new bounties on local, and though the /bounty dedicated page worked fine, the minted hackathons did not appear in the Bounty List on 

http://localhost:3000/organization/OpenQDev

or 

http://localhost:3000/contests

**Comment by ArcAnya** [comment]
Is this still happening? I pulled all latest changes (except for CoinAPI for which I had to revert changes from Monday/yesterday) and can see newly created bounties fine on both links:
Might have been solved with #1390 @Christopher-Stevers ?

![image](https://user-images.githubusercontent.com/75732239/220321852-b4c04ef3-5d8b-44ea-a23b-54ac37b72d9e.png)
![image](https://user-images.githubusercontent.com/75732239/220321897-4d025dcb-0d9c-4b91-9040-3b70701e0137.png)

**Comment by Christopher-Stevers** [comment]
It seems to be on and off depending whether coinapi and event listener are working.
