### ISSUE TITLE
Redesign footer?

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#1412]
Related to #1405 
With the latest additions (terms of use / privacy policy / batch page) the footer starts looking crowded. I'd suggest copying Github's design here - which I believe looks good also in mobile version:

Note: if we'd have more links / info to add down there, then maybe buildspace.co could be a good example - but I prefer Github's design as long as we have about the amount we currently show

![image](https://user-images.githubusercontent.com/75732239/220271961-07b5b932-ef0a-4e33-b88d-e5f2e37a522a.png)
![image](https://user-images.githubusercontent.com/75732239/220272259-9a7cdf6a-c6d2-4322-add6-9f63e8d5617d.png)

**Comment by rickkdev** [comment]
I actually would like to move away this year from the Github design guide and find our own style.

Something like this (all pages that we don't have for now you can leave out)

![footer2](https://user-images.githubusercontent.com/28826387/220326759-d411117c-5758-4526-9507-1b35b456a760.png)
