### ISSUE TITLE
Bounty says fully funded even though TVL < Budget

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1417]
https://staging.openq.dev/contract/I_kwDOGWnnz85e_fEq/0xeeed264eb7e6af3d123c5ce329639882dd2e6981?invoiceable=false

![Screenshot 2023-02-21 at 9 44 40 AM](https://user-images.githubusercontent.com/93455288/220392138-1d16c1e9-67a6-4fc3-987f-4e9bdf8d90ca.png)

**Comment by ArcAnya** [comment]
Weird, it's fine on my end:

![image](https://user-images.githubusercontent.com/75732239/220393786-00c2bcfc-6231-4261-a8ae-c238df525ea9.png)
