### ISSUE TITLE
explore page extra padding

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Frontend#1418]
![padding](https://user-images.githubusercontent.com/28826387/220403196-29819433-1021-46b3-aa23-be89cb0cecc5.png)

**Comment by rickkdev** [comment]
<img width="899" alt="responsiveness" src="https://user-images.githubusercontent.com/28826387/220968459-6a3cea81-27fb-4651-a47d-ba815b25f1c7.png">


Also on my laptop with smaller screen things dont look super great. We need to get a bit fine tuned on media queries here

**Comment by ArcAnya** [comment]
- [x] border von introducing OpenQ sollte auf keinen fall mit dem bild rechts (laptop dude) überlappen und ordentlich abstand haben dazwischen
- [x] was ich auf jeden fall wichtig finde ist dass das bild rechts mit dem laptop dude auch padding hat unten zu hackathons for you wie im screenshot
