### ISSUE TITLE
Many decimals appearing when entering 34.2 as input on mintbounty

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#1427]
Minting a fixed contract on local, with Link, one of the amounts being 34.2 triggers weird behavior:
Also happens with MATIC and with 34.3 - seems to be with .2 or .3 decimals in certain nbs (2.2 or 2.3 or 22.3) - also happens on setpayoutschedule

![image](https://user-images.githubusercontent.com/75732239/220551952-95e74f8e-d218-42b1-98d1-8c0d09d1cc9c.png)
![image](https://user-images.githubusercontent.com/75732239/220560475-68adc56a-cb22-4512-9f56-ebf96acfdd8d.png)

**Comment by ArcAnya** [comment]
Problem seems to be in this line `const payoutVolumeInWei = tier * 10 ** _payoutToken.decimals;` and related to rounding in JS: https://stackoverflow.com/questions/21472828/javascript-multiplying-by-100-giving-weird-result

**Comment by FlacoJones** [comment]
possibly solvable with BigInt?

**Comment by ArcAnya** [comment]
https://www.avioconsulting.com/blog/overcoming-javascript-numeric-precision-issues
