### ISSUE TITLE
btn-primary doesn't have filling when not hovered

### ISSUE THREAD

**Issue by Christopher-Stevers** [OpenQDev/OpenQ-Frontend#1435]
Not sure if this a bug or a feature. It looks kinda cool imo
![image](https://user-images.githubusercontent.com/72156679/220750321-969667e9-a6db-4e61-b057-91a0d34c1272.png)

**Comment by FlacoJones** [comment]
Should be the same as the other buttons, green fill

**Comment by ArcAnya** [comment]
Weird one - can't reproduce on local, but clearly see it on Staging/Prod.
It seems like the bg-color property is there but "striked out" - but I don't see any reason for it to be overriden as there is no background color property declared that could replace it (the only possibility would be bg-default when another state is happening, but then we would have a different bg-color showing)

Note: I see the same pb with btn-primary on the "Your Email" page on user profile - but never on the "new contract" button


![image](https://user-images.githubusercontent.com/75732239/222128746-1cbc114b-163e-454c-8c83-3df6d47de05f.png)
![image](https://user-images.githubusercontent.com/75732239/222128994-8c08fb98-d378-4ead-b4fe-309a2c1c67b7.png)
