### ISSUE TITLE
Border around inputs is overlapping

### ISSUE THREAD

**Issue by Christopher-Stevers** [OpenQDev/OpenQ-Frontend#1436]
In the MintBountyModal the sponsor input needs more padding above it.
![image](https://user-images.githubusercontent.com/72156679/220750478-aa904b85-6eaf-4dfc-99f4-234b9d59020f.png)

When setting tier values (not sure if this in the modal or admin page )  it needs more padding above it as well becauase its being overlapped.
![image](https://user-images.githubusercontent.com/72156679/220750550-a76b416b-12a9-45dc-b9ef-4d881ca2b942.png)

**Comment by ArcAnya** [comment]
Which browser / device are you using? On Brave & Mozilla on Desktop and on Brave on mobile this looks fine to me:
![image](https://user-images.githubusercontent.com/75732239/220958254-0547ab86-9acb-4b0e-9f36-cb63ef3a051a.png)
![image](https://user-images.githubusercontent.com/75732239/220958335-649f2238-456f-468e-bf82-df5e4aa3334d.png)
