### ISSUE TITLE
Associate user takes a minute but we aren't waiting for it in the UI

### ISSUE THREAD

**Issue by Christopher-Stevers** [OpenQDev/OpenQ-Frontend#1438]
@alo9507  there is a lag time between txn hash coming back to the frontend and the transaction for associating the wallet going through.
![image](https://user-images.githubusercontent.com/72156679/220750954-2de114ab-efac-4fd3-97f9-c5b553a55231.png)
Do we need to change the oracle to make it take longer.
I'm just imaging someone associating there wallet and not being able to claim right away

**Comment by FlacoJones** [comment]
Adopt a `Pending -> Success` model here. https://stackoverflow.com/questions/74810434/create-a-transaction-object-in-ethers-with-transaction-hash

OZ Defender Autotask returns the txn response.

We can `await` this and show pending.

Then once mined, show success
