### ISSUE TITLE
Error on local on first mint

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#1518]
Received the following error (but mint was successful)

![image](https://user-images.githubusercontent.com/75732239/222504736-51a0e28b-b343-411e-b3e2-14bfe9a6fa77.png)

**Comment by FlacoJones** [comment]
Is this reproducible? definitely would be critical priority 1 if this happens while deployed

**Comment by ArcAnya** [comment]
So far only happened several times on local

**Comment by ArcAnya** [comment]
Looked into it - after feedback from Chris and given I only saw this on local, will keep it for after our deadline

**Comment by ArcAnya** [comment]
Closing it for now as it hasn't happened in a long time to me
