### ISSUE TITLE
Logged but not logged in?

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#1519]
This issue has been there for a while - the "Deploy Contract" button is disabled and shows I need to be logged in when I am logged in.
However - this time - I was able to mint a contract already, and now it shows this tooltip when I am obviously logged in and just have minted a contract...?

![image](https://user-images.githubusercontent.com/75732239/222505462-83284c93-8bac-443a-acec-174e4abf86e3.png)

**Comment by FlacoJones** [comment]
Yes i experience this every time too on a fresh page load. Always have to reload for it to pick it up.

my guess - the mintbountymodal is initialized/mounted before we retrieve the `checkAuth` data, and isn't updated after that comes in.

Maybe we need to add `accountData` to the dependency array of some useEffect on mint bounty modal?

**Comment by Christopher-Stevers** [comment]
Hmm, didn't think this was showing up in staging.

**Comment by Christopher-Stevers** [comment]
Can you confirm this is happening on staging? I've noticed this many times local, but that's something to do with the local oauth token existing when the new boot is run.

**Comment by ArcAnya** [comment]
Don't think it has happened to me yet on staging - if it does I will report - think we should still fix this but in that case not a prio right?

**Comment by Christopher-Stevers** [comment]
don't think its really an issue tbh, since its just do to the fact that the cookie stays in the browser when the entire stack, including mongodb is rebooted, which should never happen in prod
