### ISSUE TITLE
Glitchy hackathon list while loading bounties

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1520]
When i go to hackathons on staging and begin interacting with the page before all bounties are loaded (such as click on All Issues tab) there are a few glitchy things, like it forcing me back to the Ready for Work tab

Anyone else seeing this? I assume its a render update that reset the tabs or something once all data is loaded?

**Comment by FlacoJones** [comment]
That's really the main glitch on staging. For the first 5 seconds it just keeps snapping back to "Ready to Hack" when im trying to view "All Issue"

**Comment by ArcAnya** [comment]
Unsure about this one - I can't see it on Staging but also because I see only my new issues.
Doesn't happen on local - I'll have a look again once staging is updated if it keeps happening
