### ISSUE TITLE
Staging: deposit of small value not showing up at all in the list of deposits

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#1538]
Related to #1535 and #1536 - Maybe not super important because it's for very small values, but I'd always prefer it shows up on our website somehow - especially if a funder needs to top up with a very tiny amount to handle weird rounding errors as mentioned in #1427 and #1536 

https://staging.openq.dev/contract/I_kwDOHlavZM5WFV4J/0xfbaf693fe6a6d6c38c4d2e0eb0799a453e76d05b?invoiceable=false
![image](https://user-images.githubusercontent.com/75732239/222705094-fff0a4db-cb8a-4d2f-953e-5efd0329eedd.png)
![image](https://user-images.githubusercontent.com/75732239/222705139-d4c0d2ce-4cd9-44a3-b750-aec3863e4f8e.png)

**Comment by Christopher-Stevers** [comment]
Not able to replicate, may have fixed already
