### ISSUE TITLE
All hackathon bounties should be under All Issues

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1555]
I think we had an issue for this before, but it's happening on prod:

https://openq.dev/hackathons

**Comment by ArcAnya** [comment]
Seems like tacled in #1555 ?

**Comment by Christopher-Stevers** [comment]
yeah, i think maybe the fix just didn't get deployed to prod

**Comment by Christopher-Stevers** [comment]
turns out there was edgecase that wasn't working, should be good now
