### ISSUE TITLE
Staging / Mozilla: scroll bar with submenu doesn't look very good

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#1566]
![image](https://user-images.githubusercontent.com/75732239/222923756-eeb73b0e-6b59-4d01-94d9-d9c7bb5b7c75.png)

**Comment by FlacoJones** [comment]
Duplicate of https://github.com/OpenQDev/OpenQ-Frontend/issues/1549

**Comment by ArcAnya** [comment]
Not exactly - currently the scrollbar will happen on smaller devices, so it's going to keep looking ugly on mozilla even after solving #1549
