### ISSUE TITLE
Staging: remove "insolvent" & "current target budget" when bounty claimed / closed

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#1577]
![image](https://user-images.githubusercontent.com/75732239/222961669-42f97df9-8970-45c3-ae7a-d8890ae3b8ff.png)

**Comment by ArcAnya** [comment]
Guessing you're working on this one then @Christopher-Stevers ?

**Comment by Christopher-Stevers** [comment]
yep, I'm working on it.
