### ISSUE TITLE
Suggestion: add "Claimed" to claimed submissions 

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#1579]
Low prio since we already have the Claim Overview - but it would be neat to see which winners have claimed their bounty or not

![image](https://user-images.githubusercontent.com/75732239/222961777-3a895faa-da01-4d70-b310-e89f60ed783a.png)

**Comment by FlacoJones** [comment]
```
{
  bounties(where: {bountyType: "3"}) {
    claims {
      tier
    }
  }
}
```
