### ISSUE TITLE
updated footer with audit informations

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Frontend#1581]
we need to update the footer with Sherlocks audit report

**Comment by Christopher-Stevers** [comment]
@rickkdev I removed the "not audited" text, but is there a link I can put in there to Sherlock's audit?

**Comment by rickkdev** [comment]
@alo9507

**Comment by FlacoJones** [comment]
Still haven't heard from them about a publishable report. Will ask again now.

**Comment by FlacoJones** [comment]
[2023.03.22_-_Preliminary_-_OpenQ_Audit_Report (1).pdf](https://github.com/OpenQDev/OpenQ-Frontend/files/11056446/2023.03.22_-_Preliminary_-_OpenQ_Audit_Report.1.pdf)

**Comment by ArcAnya** [comment]
This one seems closed - correct?
