### ISSUE TITLE
React errors in console

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1587]
Found these three errors on the user profile page

<img width="1680" alt="Screenshot 2023-03-08 at 1 03 28 PM" src="https://user-images.githubusercontent.com/93455288/223811778-aa918299-ff75-4c18-ad0e-13cb4476ed07.png">

**Comment by ArcAnya** [comment]
Think I might've just seen what it's related to on local -on it:

![image](https://user-images.githubusercontent.com/75732239/224030363-8a37ab0c-72b2-4a01-928f-e19dab0d8785.png)
