### ISSUE TITLE
Batch mint bounty preview card showing 0 TVL

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1589]
[EthDenverBounties - Sheet2 (1).csv](https://github.com/OpenQDev/OpenQ-Frontend/files/10893259/EthDenverBounties.-.Sheet2.1.csv)

**Comment by Christopher-Stevers** [comment]
![image](https://user-images.githubusercontent.com/72156679/224021244-2224d89f-0019-4e50-a55d-48fcc0be7d5d.png)
Not seeing that issue here.
