### ISSUE TITLE
Frontend crashes on https://staging.openq.dev/organization/SporkDAOOfficial

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1590]
Try to reproduce yourself

<img width="1257" alt="Screenshot 2023-03-05 at 4 48 19 PM" src="https://user-images.githubusercontent.com/93455288/222993060-8162c5fb-8164-445f-ad60-6f5d670630e4.png">

**Comment by ArcAnya** [comment]
Can't reproduce - looks fine here on both staging & local:

![image](https://user-images.githubusercontent.com/75732239/223037190-54e9be2d-c254-4991-9968-71316ef90093.png)

![image](https://user-images.githubusercontent.com/75732239/223037237-cdda9b2f-9388-4a22-877f-5acbc6ab10ce.png)

**Comment by Christopher-Stevers** [comment]
wasn't able to replicate either
