### ISSUE TITLE
Two submissions from same person don't show up on Refresh

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1609]
I made and then claimed this PR: https://github.com/OpenQDev/OpenQ-TestRepo/pull/944

I later made this PR: https://github.com/OpenQDev/OpenQ-TestRepo/pull/946

Both were reflected here:

![Screenshot 2023-03-07 at 5 40 09 PM](https://user-images.githubusercontent.com/93455288/223580615-31885cc6-36a5-4499-b579-f3471e0fcec3.png)

Under `Submissions`, when I click Refresh, it fails to show me the new PR so i could claim it while testing:

![Screenshot 2023-03-07 at 5 41 47 PM](https://user-images.githubusercontent.com/93455288/223580758-5881b36b-fbae-4bdf-9074-54318453da69.png)

**Comment by ghost** [comment]
It's possible this is a problem in the GithubProxy, but may also be FE

**Comment by Christopher-Stevers** [comment]
Nope, its definitely FE. We don't have a way of managing multiple submissions by the same user in the invoice server atm, so we only allow users to select 1 winner.
