### ISSUE TITLE
Prod/Staging: Login doesn't seem to work properly

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#1620]
Probably a first-time-login problem? Lmk if this happens to you - struggled but after 5-10 min or so I haven't experienced it anymore

- had to try login a couple of times (it was getting stuck on the github login page on staging or prod - using a private window)
- finally managed to login but my profile page to which I got redirected doesn't show all my info (see below)
- if I click on my profile it sends me to usre/undefined
- I have to sign out and sign in once again for everything to work properly

![image](https://user-images.githubusercontent.com/75732239/223939738-4c63d9dd-7f23-4933-8b5a-430267da80b0.png)
![Uploading image.png…]()

**Comment by Christopher-Stevers** [comment]
Haven't had any issues with this.

**Comment by ArcAnya** [comment]
OK thx - closing but if it happens again we know it's a "thing" ;)
