### ISSUE TITLE
Platform based Reviewing for Tax Forms

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Frontend#1637]
Currently reviewing happens via PR comments. Better would be within the platform

First Step:

Adding decline button on review page

- the www.openq.dev/requests page will look like this:
![request-page-one-request](https://user-images.githubusercontent.com/28826387/213493028-cc81879b-ff68-4e7d-a556-0a13d6b64f04.png)

If form is not correct you can decline and add a comment what should be changed:

- [x] decline button will open model to add description why W8 was declined:
![decline request](https://user-images.githubusercontent.com/28826387/213472359-1295383a-f161-49a7-a5ad-cf75c450a041.png)

Step 2

- [ ] if request was not accepted we will notify the builder in the claim page & via email which will include a link with the bounty claim page to then read the notification 
- [ ] in the notification message the rejection messaged will be added
![required-w8-fail](https://user-images.githubusercontent.com/28826387/213476662-61c8a675-c02f-4b86-9aa9-587b35fa2c71.png)

Step 3 continue the loop until accepted

**Comment by FlacoJones** [comment]
@Christopher-Stevers so in the API, i know we have the Requests type.

Would we be able to add a field like `changeRequested`, and a string like `changeReason`?

Then in Requests, in the org and the winner, having a "Pending" "Change Requested" and "Accepted" state?

**Comment by Christopher-Stevers** [comment]
yep, it already exists, its just a matter of figuring out the authentication for it.
