### ISSUE TITLE
If you are not logged in, you cannot pay out a bounty, but the message why is wrong.

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Frontend#1650]
If you're not logged in, you can't mint a bounty. It tells you that you are on the wrong network (which I was not) instead of requiring you to log in to mint.

Also while working on this fix, reduce the size a bit of the loading icon it should have roughly the same size of the font:

(looking at other loading icon animations I think they could also be a bit smaller (like the github refresh button loading icon)

![size](https://user-images.githubusercontent.com/28826387/225069245-b29a5789-d83f-4f65-9344-d016d64e2031.png)

**Comment by Christopher-Stevers** [comment]
@rickkdev how did you run into this error? I can't reproduce it.

**Comment by rickkdev** [comment]
> @rickkdev how did you run into this error? I can't reproduce it.

strange now it works for me too to mint a bounty without being logged in. Maybe we should change that @alo9507 ?

**Comment by FlacoJones** [comment]
You can't even see Connect Wallet without being logged in...confused how you could mint without being logged in given that?

Left over wallet connection from previous load?
