### ISSUE TITLE
claim not working in staging & padding for claim button

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Frontend#1652]
edit: after trying 5 times it worked here is the full console before it worked:

![console](https://user-images.githubusercontent.com/28826387/225078415-cd556809-0af2-4424-8d3e-303d7f7d6044.gif)

![current integration test error](https://user-images.githubusercontent.com/28826387/225077499-17065799-93e5-48f3-bacc-94698af409a0.gif)

- full integration test is currently not working 
- please adjust padding between claim your rewards title and button to the correct size

**Comment by FlacoJones** [comment]
I wasn't able to reproduce this one either

**Comment by FlacoJones** [comment]
i guess just address this: `please adjust padding between claim your rewards title and button to the correct size`

**Comment by Christopher-Stevers** [comment]
already addressed
