### ISSUE TITLE
tax form pending process UI fix request

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Frontend#1660]
![pending process upload UI](https://user-images.githubusercontent.com/28826387/225132227-7fbf38e9-0fc6-4449-90db-fff87d3634e0.png)

- [x] pending button padding left right is too much please use our standard design process based on github guidelines
- [x] Uploaded updated button is not centered vertically (items-center)
- [x] input field has not same height as buttons
- [x] I think sent button is not perfectly centered as well just that padding is equal everywhere

- [x] check that all those requirements above are also fulfilled in the claim page for other buttons across all states

**Comment by ArcAnya** [comment]
related to #1644
