### ISSUE TITLE
decline process loading icon for button/ text field

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Frontend#1661]
![no loading process](https://user-images.githubusercontent.com/28826387/225133602-a6d80e24-fc5a-4886-9cd5-24312f8219a5.gif)

- When clicking decline add some loading icon at the position where the text is to not make it look like its empty and then replace the loading icon with the success message

**Comment by Christopher-Stevers** [comment]
Will add some loading text - I think it would look more appropriate.
