### ISSUE TITLE
Custom loader on Next.js rendering wait

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#167]
Steps to Reproduce loading:
1. Go to localhost:3000
2. Click on an organization
3. In the lower right, you'll see a little Next.js icon loader pop up

Can we hook into that render process and show our own loader? I don't like our tech stack seeping through to the user, and the lag is noticeable after I click an org.

**Comment by Christopher-Stevers** [comment]
Can't reproduce.
