### ISSUE TITLE
Still says "1 New Request" even after i have accepted it

### ISSUE THREAD

**Issue by ghost** [OpenQDev/OpenQ-Frontend#1677]
<img width="1028" alt="Screenshot 2023-03-17 at 11 37 44 AM" src="https://user-images.githubusercontent.com/32375569/225965421-b8b0377f-19ab-4e38-947c-81c5b8b3fb80.png">

**Comment by Christopher-Stevers** [comment]
hmm . . . just going to remove 'new' for now. Logic for counting which requests are new is to complicated at the moment to be worth it.
