### ISSUE TITLE
How to automatically go to "Claim" tab when navigating to a bounty

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1678]
When people click the tierWinner notification on the bell, we already direct them right to the correct bounty.

Id also like to auto-focus the Claim tab to make it dead simple.

Is there a way to do this? A query string on the URL i can add?

**Comment by Christopher-Stevers** [comment]
Add   `sessionStorage.setItem(address, 'Claim')` before you push. This set up before - just pushed a bug fix for it, though so you may want to pull to see it work.

**Comment by FlacoJones** [comment]
This is tough because the link is clicked in an email off of our domain

**Comment by Christopher-Stevers** [comment]
I guess I can add something that takes the query param
