### ISSUE TITLE
Where to direct for W8 form update requests?

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1679]
When people click this requestDeclined notification, what would the best place be to send them? The claim tab of the bounty?

<img width="398" alt="Screenshot 2023-03-19 at 12 52 06 PM" src="https://user-images.githubusercontent.com/93455288/226196768-cbe229d3-b504-4102-91d2-0ea8c93b6ca3.png">

**Comment by Christopher-Stevers** [comment]
Yep, they should be sent to the claim tab of the bounty.
