### ISSUE TITLE
Use dompurify with dangerouslySetInnherHtml

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1680]
So i asked ChatGPT about this (https://legacy.reactjs.org/docs/error-decoder.html/?invariant=425) React error we keep getting in the console.

It's happening because of our use of `dangerouslySetInnerHTML` in `ActionBubble` and `BountyCardDetails`

So for one thing we should probably sanitize this html, otherwise people could perhaps inject dangerous code in a Github issue (i think Github may actually already sanitize)

<img width="782" alt="Screenshot 2023-03-19 at 1 17 49 PM" src="https://user-images.githubusercontent.com/93455288/226198434-e4c0790e-43e3-420d-b599-19d9b297d2a6.png">

The other thing, I don't know how to get rid of this error since we do need to somehow render the `bodyHTML` from the issue.

Any ideas?

**Comment by Christopher-Stevers** [comment]
Hmm . . . yeah I think we can trust github and prisma on this one. I'll try dom.purify just to remove the error though.
