### ISSUE TITLE
W8 Form email sending twice, and has undefineds in it

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1682]
W8 Form email sending twice, and has undefineds in it

![Screenshot 2023-03-19 at 5 10 24 PM](https://user-images.githubusercontent.com/93455288/226212680-e0ecf13b-4f4d-4728-98b6-e1f5ac78fb93.png)

**Comment by FlacoJones** [comment]
Maybe the Frontend is posting to the mutation in the API twice?

Either that, or somewhere in Email server its getting called twice, which seems less likely

**Comment by ghost** [comment]
What was this one blocked on again? I know why it sent twice, was user (me) error.

But what about the `null`?

**Comment by Christopher-Stevers** [comment]
I was waiting for knock code so I couldn't really do any manual testing locally because my email server was crashing
I'll test it now, but I think my fixes should be enough.
