### ISSUE TITLE
Wrap all dates in a client only component

### ISSUE THREAD

**Issue by ghost** [OpenQDev/OpenQ-Frontend#1688]
The DOM purify is good, but we still have a mismatch between server rendered and frontend rendered code causing these errors on most pages.

It's thrown anytime DOM updates are triggered by things occuring outside of a `useEffect`, which we do with `dangerouslyInjectHTML`

Any idea on how we fixed this in the past?

<img width="1680" alt="Screenshot 2023-03-20 at 5 37 06 PM" src="https://user-images.githubusercontent.com/32375569/226481151-7b3ed44f-1c89-4026-b05c-c66211f3f3d7.png">

**Comment by Christopher-Stevers** [comment]
we fixed this in the past by using useEffect to update date fields . . . I wonder if this one is something to with dom purify.

**Comment by Christopher-Stevers** [comment]
Not sure why they even expose these errors since its not actually noticeable for the user.

**Comment by Christopher-Stevers** [comment]
Attempting to close this by turning off react-strict-mode.
I don't know why this isn't showing up locally - I think it might be something to do with nesting inside of p tags, but don't really want to change all the p tags in the app.
