### ISSUE TITLE
Error with new document.cookies approach

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1689]
So I noticed that after the first render, if i reloaded the page, then Knock ceased to be able to connect over wss. 

I diffed the URL between when it worked (left) and when it didn't (right):

<img width="1456" alt="Screenshot 2023-03-20 at 5 59 18 PM" src="https://user-images.githubusercontent.com/93455288/226484018-c2528e27-8a45-47ea-84ce-6d02f1514a23.png">

Somehow, our google analytics token is getting caught up in the regex we're using to fetch it

**Comment by FlacoJones** [comment]
Should be fixed with a quick utils test on the regex, if that is indeed the issue. I suspect it is because when i reverted to the old approach, it started working again.

**Comment by Christopher-Stevers** [comment]
k, will fix this. I had to change it because the old approach isn't supported in Firefox.
