### ISSUE TITLE
Create a preview for Tier Winner Batch

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1703]
Staging now has a nice Tier Winner batch method similar to our Batch Mint.

I'd also like a preview for these. A very simple one

Must show:

- The github user's LOGIN and AVATAR IMAGE
- The github issue description they are winning
- The TIER they won and the TIER AMOUNT they are winning

Some repurposed `BountyCardLean` should work?

**Comment by FlacoJones** [comment]
Since this page + CSV are still in beta, i'd suggest approaching this using mock data. Just a component that accepts the already-processed props and displays them

**Comment by Christopher-Stevers** [comment]
@FlacoJones what does the csv look like? I'm as far as I can go without it.

**Comment by FlacoJones** [comment]
It has this info

It's quite stable now - in staging

[tierWinner_mini.csv](https://github.com/OpenQDev/OpenQ-Frontend/files/11105734/tierWinner_mini.csv)
