### ISSUE TITLE
Bounty description should be pinned to the top of the /contract pages

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1719]
Now that we have many PRs, the Description keeps getting lower and lower

Similar to the Github Issue action timeline, we should keep the description pinned to the top, and all events after that go below it

**Comment by Christopher-Stevers** [comment]
So should we change the order of all the other events as well? I think it make sense if they are in chronological order.

**Comment by ArcAnya** [comment]
Suggested change in PR #1730: 
removing the description from the "minted contract" ActionBubble & placing it right below the title - I don't think it's necessary to have the description inside the minted contract action bubble - I believe it's enough to know when the contract was minted and have the description with the title above

Like so:

![image](https://user-images.githubusercontent.com/75732239/228508014-e0d87839-faab-4a6f-b95b-52b077a19f33.png)
![image](https://user-images.githubusercontent.com/75732239/228508296-8e30f904-8c68-4b3d-812f-fcb555cbeae7.png)
![image](https://user-images.githubusercontent.com/75732239/228508347-3ada638e-2b71-483a-a0b4-5c67004cc655.png)
![image](https://user-images.githubusercontent.com/75732239/228511436-900c2f97-73d3-456a-b686-69028c697337.png)
