### ISSUE TITLE
Include amount of USDC in the Claim explanation

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1733]
Replace "off" with tier amount - this was a bounty funded in MATIC, which might be causing the issue.

Let's do this more robustly by showing VOLUME - SYMBOL

<img width="763" alt="Screenshot 2023-03-29 at 7 20 43 PM" src="https://user-images.githubusercontent.com/93455288/228696674-971118cc-3401-4ba6-9339-e34394696e82.png">

**Comment by ArcAnya** [comment]
My bad - somehow focused on the dynamic wallet address & forgot the token part
