### ISSUE TITLE
On staging, receiving EMAIL_NOT_SENT

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1734]
I received this error when attempting to test send on staging, no logs in the email server. Response was simply "EMAIL_NOT_SENT"

<img width="890" alt="Screenshot 2023-03-29 at 7 25 01 PM" src="https://user-images.githubusercontent.com/93455288/228697063-bd3e2001-77fd-4224-929c-5a4983ba1ab2.png">

**Comment by ArcAnya** [comment]
On my end, accepting / declining also seem not to work on staging
For Declining it says "successful" & I get a network response but I receive no emails
For Accepting nothing seems to happen - & I get an error in the console

![image](https://user-images.githubusercontent.com/75732239/228844986-a14a86de-5351-45e4-899d-6ce31b16f572.png)
![image](https://user-images.githubusercontent.com/75732239/228845364-93d9ba98-e547-4dc6-9362-f3ec74274079.png)
