### ISSUE TITLE
Add an explanation about "tier selection" on Submissions page

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1736]
People don't get they can't claim yet, understandably.

Let's add a banner in the same style as this one:

![Screenshot 2023-03-30 at 11 43 18 AM](https://user-images.githubusercontent.com/93455288/228906743-4585f2cf-fad3-4ed9-a860-68f652ac071c.png)

Ideas for where to add it:
- Directly on the /contract bounty details View tab, the first thing visitors see. Detect that the logged in GH user has an open submission, and then show it if they do have a submission
- Permanently on the Submissions page, no need for any user authentication
- Showing the Claim tab at all times, but just showing this banner if the logged in user hasn't been selected as a tier winner yet

**Comment by Christopher-Stevers** [comment]
I'm going to go with the third option.

**Comment by ArcAnya** [comment]
I believe this one has been done (closing it):
![image](https://user-images.githubusercontent.com/75732239/229051329-e0aa49b0-e3db-4789-85d7-0846b9443d86.png)
