### ISSUE TITLE
Prod: requested changes showing in email BUT NOT on FE

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#1774]
On prod I declined a request on https://openq.dev/contract/I_kwDOHlavZM5f8hO_/0xe13d80be2b23833686F4543E82949CBc57273bbb

Could see the decline message on the email and also received a notification for it on openq.dev
But could not see the message on the FE Claimpage

![image](https://user-images.githubusercontent.com/75732239/230678490-da28cd11-7455-4505-99c1-d9b80544fb8f.png)
![image](https://user-images.githubusercontent.com/75732239/230678631-2c40a0f7-8a62-4755-bef6-086073c173b8.png)
![image](https://user-images.githubusercontent.com/75732239/230678650-54151def-24b2-4ab1-8466-6588b35d62df.png)

**Comment by Christopher-Stevers** [comment]
Hmm . . . wasn't able to repo this

**Comment by Christopher-Stevers** [comment]
![image](https://user-images.githubusercontent.com/72156679/230997161-87a77c8f-6de1-4ea1-9c31-24e4693ef436.png)

**Comment by ArcAnya** [comment]
Was that on staging or on local? On prod it seems to be an issue - happened to users & to me on Friday - I checked right now and still don't see the requested changes on my FE

**Comment by Christopher-Stevers** [comment]
I think that was prod, I'm going to test it locally.
