### ISSUE TITLE
Prod & Staging: list of requests seems not to allow for several requests per user

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#1776]
Experienced the issue both on staging and prod:
When one same github user sends 2 different requests for W8/W9, we just end up seeing the latest request (no matter if the earlier request(s) has been accepted or not) on the /requests/ page

**Comment by Christopher-Stevers** [comment]
Not sure what this means exactly. I'm seeing multiple requests as long as those are for different bounties. We aren't supposed to be showing having multiple requests by the same user for the same bounty.

**Comment by ArcAnya** [comment]
On my end - on Friday - both on staging and on prod - when I created a request for a different bounty it removed the other request of that same github user for the first (different) bounty from the list. Have you tested this recently?   

So, for instance, the request list I'm currently seeing on my request page on staging is incomplete - the bounty "issue to check winners" has a second request that was never accepted from my second github account, which I can see on the staging subgraph:

(Note that I can still access that "disappeared" request from the email link, however)

![image](https://user-images.githubusercontent.com/75732239/231071851-e3c1b1ed-f570-49d8-92d4-05a024f42f99.png)


![image](https://user-images.githubusercontent.com/75732239/231070416-e619668b-c348-4846-806f-8eabd32a2bf9.png)

**Comment by Christopher-Stevers** [comment]
Hmm, I haven't recently.
Assigning it to myself.
