### ISSUE TITLE
Bug in Dashboard Overview - showing unassigned tier winner, but is assigned

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1809]
Hunch - React rendering lists + the key for the items

https://openq.dev/contract/I_kwDOI-Vpys5fS4YC/0xef8abbc06ac1186835de0c0920b2aee1a3396bb8

![Screenshot 2023-04-14 at 2 50 55 PM](https://user-images.githubusercontent.com/93455288/232142114-f83c5159-25f2-42d7-9a70-7e5672b1e193.png)

**Comment by ArcAnya** [comment]
Tried filtering, defiltering but on my end it looks good atm:
I'll see if it happens to me on local - I think it might rather be related to loading times - I'll improve the "loading" state handling so we can in any case know more precisely what's happening

![image](https://user-images.githubusercontent.com/75732239/232444089-975e664d-0263-4ecb-b46c-b5563a9a7383.png)
