### ISSUE TITLE
Same bounty appears twice in prod search

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1823]
Notice the different number for Watching - is this double entered in the API or something?

![Screenshot 2023-04-18 at 4 27 00 PM](https://user-images.githubusercontent.com/93455288/232909025-bc991285-d5ad-431e-9cd3-e958f8154fdb.png)

**Comment by ArcAnya** [comment]
Had the same issue yesterday on a bunch of bounties on repo/org page (while it was fine on hompepage) and increasing the batch size of the repo/org page to 20 fixed it.

What's interesting is that on the homepage there is no duplicate for that bounty - yet I believe the batch sizes are now the same (20)

**Comment by Christopher-Stevers** [comment]
Finally figured it out, this was an issue on the api side where ordering was becoming randomized because we had so many created on the same millisecond.

**Comment by ArcAnya** [comment]
Cool - this might be solving a remaining duplicate issue I had on the Hackathon Dashboard - lmk when the fix goes through so I can double check if this solves it
