### ISSUE TITLE
Add a number of tiers while filtering

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1850]
It would be nice to have a "total number of tiers" for when I filter

For example, I'd like to be able to answer the question "How many people have Approved tax forms, but have not yet claimed"

It can be added to the bottom right of the search/filter bar.

![Screenshot 2023-04-26 at 12 16 18 PM](https://user-images.githubusercontent.com/93455288/234652744-390f7764-52e8-43bc-96cd-cfa395371528.png)

**Comment by ArcAnya** [comment]
I think it's already there - you mean this ?
If you didn't see it then maybe it should be named or placed differently - lmk what you think

[Note: currently the stat is not always correct before of the "Loading..." issue, but I hope that my PR #1844 will solve that]

![image](https://user-images.githubusercontent.com/75732239/234795116-49902a27-3a44-4e97-9325-bd7d864b7678.png)
