### ISSUE TITLE
Staging: "sort order" as newest per default does not work 

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#1855]
But once I click on another sort order they all work well 

![image](https://user-images.githubusercontent.com/75732239/235068355-dbe13e07-70cf-4a8b-be61-014f2e0ab786.png)

**Comment by Christopher-Stevers** [comment]
Closed by https://github.com/OpenQDev/OpenQ-Frontend/commit/8f5effd4a67d12d5618bd26b119a2ab5b774dccc
