### ISSUE TITLE
Claim button disabled, though funds exist

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1864]
![image](https://user-images.githubusercontent.com/93455288/235937436-e2856c3a-38fb-4c5a-9793-86dcf3dabd66.png)

https://openq.dev/contract/I_kwDOI-Vpys5fShW4/0xafdc255e1aca447cd67c167c15f752cfd8ebf075

**Comment by ArcAnya** [comment]
same as #1858
