### ISSUE TITLE
Claim getting rejected with NO_ASSOCIATED address even though user does have associated address.

### ISSUE THREAD

**Issue by Christopher-Stevers** [OpenQDev/OpenQ-Frontend#1868]
Claim getting rejected with NO_ASSOCIATED address even though the account I'm using does have an associated address.
Here's the logs
Params for 
 ` console.log(externalUserId, closerAddress, prUrl, tier);`
```
MDQ6VXNlcjcyMTU2Njc5 0xD0c1a0d6CD19688CeC7612B878DaAC09805D2C95 https://github.com/SporkDAOOfficial/ETHDenver-2023/pull/456 0 
```
logs from error.
```
_app-e12cf8466807e3d3.js:33:314094
MetaMask - RPC Error: Internal JSON-RPC error. 
Object { code: -32603, message: "Internal JSON-RPC error.", data: {…} }
​
code: -32603
​
data: Object { code: 3, message: "execution reverted: NO_ASSOCIATED_ADDRESS", data: "0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000154e4f5f4153534f4349415445445f414444524553530000000000000000000000" }
​
message: "Internal JSON-RPC error."

**Comment by ArcAnya** [comment]
Issue is due to associating the same wallet to two different github accounts - which is not "allowed"
I'd suggest a better handling of this in the FE in the future

![image](https://user-images.githubusercontent.com/75732239/236204218-8bafea3e-f867-45c4-9197-6af95f53bd93.png)

**Comment by Christopher-Stevers** [comment]
I've fixed this issue but I'm still getting the same issue, when the claim progress on my issue is like this:
![image](https://user-images.githubusercontent.com/72156679/236205816-eb9bef18-4162-41e0-8449-b9aa3b2a9b30.png)

**Comment by Christopher-Stevers** [comment]
Possibly was just an issue with not having enough funds in the wallet to claim.

**Comment by ArcAnya** [comment]
Closing this for now then
