### ISSUE TITLE
TVC, TVL incorrect on partially claimed bounties

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1882]
Here is one such example, but there are many in production with similar situations that don't add up: 

https://openq.dev/contract/I_kwDOI-Vpys5fSe-7/0xfb3708a212411a8192ecf69c2a0a8dda0caab1d4

<img width="372" alt="Screenshot 2023-06-30 at 9 38 40 AM" src="https://github.com/OpenQDev/OpenQ-Frontend/assets/93455288/44ce0022-4aba-4242-9f5b-91163851a8e7">

**Comment by ArcAnya** [comment]
hmm on this one I can already see that on the subgraph the claims & payouts are not the same, 4 claims vs. 5 payouts - one payout à $1250 doesn't show up in claims on the subgraph it seems...

I'll look into how the TVC is currently calculated - it's been changed plenty times + fuzzy logic-ed at some point... not sure where it's at atm

**Comment by ArcAnya** [comment]
Seems like it's coming from the API:
![image](https://github.com/OpenQDev/OpenQ-Frontend/assets/75732239/db2a139d-65f8-4a54-9b14-412f59497d4e)


This overview is based on payouts and seems to be correct for this example (I checked on polygonscan):
![image](https://github.com/OpenQDev/OpenQ-Frontend/assets/75732239/6590599f-759f-4631-85ff-7a61746ba2f0)
