### ISSUE TITLE
Use generic ERC20 logo for tokens with no logoUri

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#217]
Like Metamask: 

<img width="195" alt="Screen Shot 2022-04-08 at 3 27 41 PM" src="https://user-images.githubusercontent.com/93455288/162525577-adfb7617-3c38-4be0-a8f7-8ce4bf49e44d.png">

**Comment by Christopher-Stevers** [comment]
Need know strategy for whitelisting vs user submitted tokens.
