### ISSUE TITLE
"Custom Token" address input in Token Selector

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#218]
We have the standard list of most used tokens, but we also want to support unlisted Governance tokens for DAOs as a core goal of OpenQ has been to get gov tokens into the hands of dev contributors.

This task it to conceive of and implement a good UI for also funding with ANY ERC20

**Requirements**

- User should be able to past a token address, see some loading, and then see the name + symbol called from the ERC20 contract. This may require a new modal.
- Should extract Symbol, Name and Decimals from the input ERC20 address and show in interface
- Use the "ERC20.svg" default logo
- Conceive of how to NOT call getTokenValues, or generally how to account for tokenAddresses that won't be available on CoinGecko. This may already work, not sure how the FE responds to null responses from CoinAPI

**Comment by Christopher-Stevers** [comment]
Need know strategy for whitelisting vs user submitted tokens.
