### ISSUE TITLE
Use React loading gradient for slow organization GitHub avatar load

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#219]
On first load, the OrganizationCard is empty while it loads the avatarUrl.

If we can't somehow speed this up, can we at least use that "react loading gradient" thing where the image is supposed to be?

**Comment by Christopher-Stevers** [comment]
Looks like next  https://nextjs.org/docs/api-reference/next/image#placeholder something for this. Will implement it when I get a chance.
