### ISSUE TITLE
Stuck on Indexing Bounty

### ISSUE THREAD

**Issue by ghost** [OpenQDev/OpenQ-Frontend#236]
We get stuck on the Indexing Bounty modal even after the bounty has been indexed an is accessible on graph queries

Confirmed by seeing "Done processing" here in the Graph logs for development: https://thegraph.com/hosted-service/subgraph/openqdev/openq-development?selected=logs

~~IDEA: Could it be because the Graph only accepts LOWER_CASED addresses? Let's revisit the retry mechanism.~~ We already lowercase the address [here](https://github.com/OpenQDev/OpenQ-Frontend/blob/development/services/subgraph/OpenQSubgraphClient.js#L50)

**Comment by FlacoJones** [comment]
IDEA: Something to do with the APOLLO CACHE:

https://www.apollographql.com/docs/react/data/queries/#nextfetchpolicy

**Comment by FlacoJones** [comment]
Check out all these: https://www.apollographql.com/docs/react/data/queries/#supported-fetch-policies

**Comment by FlacoJones** [comment]
I think this might also be why the deposits haven't been refreshing either on refresh bounty maybe

**Comment by FlacoJones** [comment]
We use `getBountyById` in [MintBountyModal](https://github.com/OpenQDev/OpenQ-Frontend/blob/8462efaa25a5e7b91168684a1a8d63c992d54782/components/MintBounty/MintBountyModal.js#L105)

But we use `getBounty` with caching options elsewhere like [here](https://github.com/OpenQDev/OpenQ-Frontend/blob/8462efaa25a5e7b91168684a1a8d63c992d54782/pages/bounty/%5Baddress%5D.js#L47)

This should be standardized to ease debugging

**Comment by FlacoJones** [comment]
~~Trying with `cache-and-network`...~~

Says this can't be used with client.query

**Comment by FlacoJones** [comment]
Let's just set to `no-cache` to isolate whether or not caching was the cause of this state inconsistency

**Comment by FlacoJones** [comment]
Solved by [commit](https://github.com/OpenQDev/OpenQ-Frontend/commit/016556b7678f7a35b9bf249a290ccab8739c1582) which adds`no-cache` 

And solved by [commit](https://github.com/OpenQDev/OpenQ-Frontend/commit/c4cb4e13971be1f5ae708c8c53daa67ed9861ebc) which adds a Fund, Refund and Claim retry mechanism on `refreshBounty`

**NOTE**

It sometimes takes up to 19 calls with a half second polling period before the new deposit is indexed, but better late than never. It does eventually re-render:

<img width="128" alt="Screen Shot 2022-04-13 at 6 44 15 PM" src="https://user-images.githubusercontent.com/93455288/163287375-19a8d49f-f2a6-44d8-b3aa-d75aff2cbe51.png">
