### ISSUE TITLE
Bounties/Issues don't auto update after minting a new bounty

### ISSUE THREAD

**Issue by VictoQ** [OpenQDev/OpenQ-Frontend#242]
steps to reproduce:

1) mint a bounty

2) fund the bounty

3) now the bounty will only appear after you reload the page (it wont appear by going to the backpage)

**Comment by FlacoJones** [comment]
We intend to fix this after switching to fetch bounties from OpenQ-API.

Without subscriptions from The Graph this is a tough one.

Iceboxing for now.

**Comment by FlacoJones** [comment]
Force reload using Next router to reload the page ONLY IF the originating page is a new bounty
