### ISSUE TITLE
Page breaks on WETH deposits.

### ISSUE THREAD

**Issue by Christopher-Stevers** [OpenQDev/OpenQ-Frontend#263]
Received a white screen with application error after I funded with WETH. Reloaded and saw my WETH deposits in a continual loading state.
Saw these errors in my console when the on pages with WETH:
![image](https://user-images.githubusercontent.com/72156679/164529177-2c7db815-6dba-430f-bd84-298305eb3008.png);
I was able to successfully claim the WETH, but the bounty details are still messed up: https://staging.openq.dev/bounty/0x2a7f748f2dca03b630cd0bb1f8ab89ceecfa98f1.

**Comment by FlacoJones** [comment]
This causes a cascading failure wherever price is shown.

Our token balance displays are not resilient.

<img width="921" alt="Screen Shot 2022-04-21 at 2 25 31 PM" src="https://user-images.githubusercontent.com/93455288/164537861-67e10267-1361-4729-a930-c86512bcc5ec.png">

**Comment by FlacoJones** [comment]
I checked the calls to `/tvl`. We never send a request for `0x7ceb23fd6bc0add59e62ac25578270cff1b9f619` for some reason

**Comment by FlacoJones** [comment]
Somewhere in the pre-flight checks in `useGetToken` this is getting disqualified
