### ISSUE TITLE
Eternally transferring.

### ISSUE THREAD

**Issue by Christopher-Stevers** [OpenQDev/OpenQ-Frontend#264]
Gets stuck on transfer when you try to send more ERC-20 ( Link) than you own.
![image](https://user-images.githubusercontent.com/72156679/164531252-c7a3cce6-e77b-4ed2-830c-4accc4c1cf3c.png)

**Comment by FlacoJones** [comment]
I thought that we disabled transfer with the "Not Enough Funds" modal?
