### ISSUE TITLE
Eternal Approving if user replaces transaction for Speed Up

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#274]
In Eth, you can resubmit a transaction with the SAME NONCE but HIGHER GAS to speed up a transaction.

MetaMask makes this available via the Speed Up button.

Because our Frontend is waiting on the transaction receipt from the INITIAL TRANSACTION, if the user chooses to Speed Up as I often do, we get the following error, and Approve continues waiting eternally for a transaction which will never finish because it's been replaced.

We need some way to detect when a transaction with that nonce is replaced, and begin waiting for the latest submitted transaction instead:

<img width="1288" alt="Screen Shot 2022-04-22 at 12 35 11 PM" src="https://user-images.githubusercontent.com/93455288/164765897-c8aa4bb1-5dd2-4f8f-8e8b-9d272ad7208f.png">

**Comment by FlacoJones** [comment]
Steps to recreate:

1. Initiate funding
2. Click speed up while its pending
3. This should make a new txn

**Comment by FlacoJones** [comment]
related to #184 , as this will be hard to "speed up" locally given txns are almost immediately confirmed

**Comment by Christopher-Stevers** [comment]
Tested in local-targeting-staging. Looks like its been resolved.
