### ISSUE TITLE
Integration Testing - Chris 4/25

### ISSUE THREAD

**Issue by Christopher-Stevers** [OpenQDev/OpenQ-Frontend#280]
Tweet text formatted badly/gramatically incorrect. 
![image](https://user-images.githubusercontent.com/72156679/165121453-0bfb163f-3cd1-49cc-ad87-299a040f2430.png);
If you haven't imported your token, choosing them can lead to an an eternal approving modal.
Might be a good idea to exposed the number of the issue on the bounties. That way its easier for the user to link it in their pr.

**Comment by FlacoJones** [comment]
Related to https://github.com/OpenQDev/OpenQ-Frontend/issues/269

**Comment by FlacoJones** [comment]
Interesting re: not having imported token.

So if someone tries to fund with USDT but doesn't have that imported in MetaMask already it never approves?

That seems odd since it's just a contract interaction, nothing MetaMask really has a say in.

**Comment by FlacoJones** [comment]
Quickswap solves this well by integrating a little "Add token" plus sign next to tokens on token list:

<img width="480" alt="Screen Shot 2022-04-25 at 10 48 09 AM" src="https://user-images.githubusercontent.com/93455288/165125607-869a9b25-e9bf-4601-8506-3cf732f6535b.png">

**Comment by Christopher-Stevers** [comment]
> Interesting re: not having imported token.
> 
> So if someone tries to fund with USDT but doesn't have that imported in MetaMask already it never approves?
> 
> That seems odd since it's just a contract interaction, nothing MetaMask really has a say in.

That how I thought it was behaving, however I tested it with BAL (which I have but can't see in my wallet and it worked fine.

**Comment by Christopher-Stevers** [comment]
Could not replicate
