### ISSUE TITLE
Disconnect, reload page, still connected

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#322]
However we are implementing disconnnect, it's not actually disconnecting Metamask.

Ensure this actually remains disconnected on reload for both Metamask and Wallet Connect or people may think we're up to something sketchy

**Comment by Christopher-Stevers** [comment]
@FlacoJones  Its actually impossible to disconnect the user in metamask from a dApp. If you look at balancer you'll see the metamask is connected after your disconnect your wallet in the UI. Right now disconnecting the wallet uses the deactivate method from web3 react which just sets the values of the web3 object to a falsy value.
Do you want me just to store whether they are disconnected or connected in local storage and then use that to disconnect them immediatly when they arrive?

**Comment by FlacoJones** [comment]
That's right. I guess this is as good as it gets then - direct access to Metamask connected accounts must not be exposed to scripting.
