### ISSUE TITLE
Remove horizontal scroll

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#345]
Can we remove the large horizontal scroll?

<img width="1680" alt="Screen Shot 2022-05-19 at 3 19 37 PM" src="https://user-images.githubusercontent.com/93455288/169397559-cc38feb5-800d-4f8d-bc04-8d63d755dbd1.png">

**Comment by Christopher-Stevers** [comment]
Could not replicate. How was this showing up @FlacoJones
