### ISSUE TITLE
Time outs for loading data from coin gecko.

### ISSUE THREAD

**Issue by Christopher-Stevers** [OpenQDev/OpenQ-Frontend#347]
Right now when coin gecko's api is down we either show skeleton's or NaN where the data it returns should be. Ideally it would be empty, or zero and the user would be notified that token prices aren't available at the moment.
This may also be necessary for displaying custom tokens.

**Comment by FlacoJones** [comment]
That makes sense. Can we show "Unavailable" for the price when this happens?

**Comment by FlacoJones** [comment]
A bounty has been minted for this issue at https://app.openq.dev/bounty/I_kwDOGAqhQc5KFb07/0xDc79d3bf0CD11682Be000d0001E92B937167C709

**Comment by FlacoJones** [comment]
A deposit of  0.01 MATIC was placed on this issue at https://app.openq.dev/bounty/I_kwDOGAqhQc5KFb07/0xDc79d3bf0CD11682Be000d0001E92B937167C709

**Comment by FlacoJones** [comment]
A bounty has been minted for this issue at https://development.openq.dev/bounty/I_kwDOGAqhQc5KFb07/0xbd9Fb59d6473DdE91F2597BDa8B138FCC7824d58

**Comment by Christopher-Stevers** [comment]
> That makes sense. Can we show "Unavailable" for the price when this happens?

Do we still need this at this point?
