### ISSUE TITLE
Center wallet connect buttons

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#352]
Let's:

- Make the highlight near full width, not just left-aligned
- Center logo and contents
- Say "Close" instead of "Back"

<img width="400" alt="Screen Shot 2022-05-22 at 12 02 30 PM" src="https://user-images.githubusercontent.com/93455288/169706927-a980ce89-72e1-4e2f-a8ed-bb58a83d8fff.png">

**Comment by Christopher-Stevers** [comment]
The metamask and walletconnect buttons should also have a 1px web-gray border around the highlighted area.
