### ISSUE TITLE
CORS for gnosis safeapp integration.

### ISSUE THREAD

**Issue by Christopher-Stevers** [OpenQDev/OpenQ-Frontend#396]
The cors policy for staging is preventing it from being used as a gnosis safe app.
#### Replication
- Go to https://gnosis-safe.io/ and open app. go to apps and try to add https://staging.openq.dev as a gnosis safe app. CORS errors show up in console.

**Comment by FlacoJones** [comment]
I get failed to fetch app manifest for staging

**Comment by FlacoJones** [comment]
Which services log errors? will add gnosis-safe.io to their CORS allowed origins

**Comment by FlacoJones** [comment]
A deposit of  0.5 Chainlink Token was placed on this issue at http://development.openq.dev/bounty/0xE01b485B21C3f4cC1Cf847d7cB3409C51C3E1Ee3

**Comment by FlacoJones** [comment]
A deposit of  0.5 Dummy ERC20 was placed on this issue at http://development.openq.dev/bounty/0xE01b485B21C3f4cC1Cf847d7cB3409C51C3E1Ee3

**Comment by Christopher-Stevers** [comment]
I'm getting the failed to fetch app manifest thing too. Might try firing up my local stack tomorrow to see what's going on.

**Comment by Christopher-Stevers** [comment]
@alo9507  can you take a look at this after promoting today's changes'? Its been working on the local stack, but not on staging.
