### ISSUE TITLE
Round token volume in Token Balances.

### ISSUE THREAD

**Issue by Christopher-Stevers** [OpenQDev/OpenQ-Frontend#419]
We need some way to handle weird balances like this:
![image](https://user-images.githubusercontent.com/72156679/172597585-80e4cb07-4adf-4471-87a4-a0b4e02827bb.png)

**Comment by FlacoJones** [comment]
A bounty has been minted for this issue at https://staging.openq.dev/bounty/I_kwDOGAqhQc5LX3zv/0x67960588F12ea78A5aDAFe649a6A0955a46f955F

**Comment by FlacoJones** [comment]
A deposit of  0.000001 Wrapped Ether was placed on this issue at https://staging.openq.dev/bounty/I_kwDOGAqhQc5LX3zv/0x67960588F12ea78A5aDAFe649a6A0955a46f955F

**Comment by FlacoJones** [comment]
A deposit of  0.01 MATIC was placed on this issue at https://staging.openq.dev/bounty/I_kwDOGAqhQc5LX3zv/0x67960588F12ea78A5aDAFe649a6A0955a46f955F

**Comment by FlacoJones** [comment]
A deposit of  0.00001 Wrapped Ether was placed on this issue at https://staging.openq.dev/bounty/I_kwDOGAqhQc5LX3zv/0x67960588F12ea78A5aDAFe649a6A0955a46f955F

**Comment by FlacoJones** [comment]
A deposit of  0.000001 Wrapped Ether was placed on this issue at https://staging.openq.dev/bounty/I_kwDOGAqhQc5LX3zv/0x67960588F12ea78A5aDAFe649a6A0955a46f955F

**Comment by FlacoJones** [comment]
A deposit of  0.0000001 Wrapped Ether was placed on this issue at https://staging.openq.dev/bounty/I_kwDOGAqhQc5LX3zv/0x67960588F12ea78A5aDAFe649a6A0955a46f955F

**Comment by FlacoJones** [comment]
A deposit of  0.0000001 MATIC was placed on this issue at https://staging.openq.dev/bounty/I_kwDOGAqhQc5LX3zv/0x67960588F12ea78A5aDAFe649a6A0955a46f955F

**Comment by FlacoJones** [comment]
A deposit of  0.0000001 MATIC was placed on this issue at https://staging.openq.dev/bounty/I_kwDOGAqhQc5LX3zv/0x67960588F12ea78A5aDAFe649a6A0955a46f955F

**Comment by FlacoJones** [comment]
A deposit of  0.0000001 MATIC was placed on this issue at https://staging.openq.dev/bounty/I_kwDOGAqhQc5LX3zv/0x67960588F12ea78A5aDAFe649a6A0955a46f955F

**Comment by FlacoJones** [comment]
A deposit of  0.00001 MATIC was placed on this issue at https://staging.openq.dev/bounty/I_kwDOGAqhQc5LX3zv/0x67960588F12ea78A5aDAFe649a6A0955a46f955F

**Comment by FlacoJones** [comment]
A deposit of  0.00001 MATIC was placed on this issue at https://staging.openq.dev/bounty/I_kwDOGAqhQc5LX3zv/0x67960588F12ea78A5aDAFe649a6A0955a46f955F

**Comment by FlacoJones** [comment]
A deposit of  0.000001 Wrapped Ether was placed on this issue at https://staging.openq.dev/bounty/I_kwDOGAqhQc5LX3zv/0x67960588F12ea78A5aDAFe649a6A0955a46f955F
