### ISSUE TITLE
Watched bounties don't disappear until reload.

### ISSUE THREAD

**Issue by Christopher-Stevers** [OpenQDev/OpenQ-Frontend#423]
Replication:
Watch a bounty.
Go to http://localhost:3000
Watched bounty should be there.
Now navigate back to bounty page and un-watch.
Now click on the home icon and navigate to the Issues tab of http://localhost:3000.
You'll still see the watched bounty, until you reload.

Solution: 
Make the home icon a plain <a> tag instead of a next <Link> we're already doing that for some other stuff to do with minting/funding.

**Comment by FlacoJones** [comment]
A bounty has been minted for this issue at https://staging.openq.dev/bounty/I_kwDOGAqhQc5LZH_J/0x2ABc523dcd78ae77e0Ac8fabAA93E978e1E94A5E
