### ISSUE TITLE
Disconnect wallet button not working

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#429]
Booting the OpenQ-Frontend repo locally (without the Fullstack boot) there is an error when clicking the "Disconnect" wallet button from: "TypeError: deactivate is not a function disconnectAccount AccountModal.js:19"

![image](https://user-images.githubusercontent.com/75732239/173012886-4cad24ae-c30a-4d61-aec1-b5ca703e1a0f.png)

**Comment by Christopher-Stevers** [comment]
Can't disconnect on local, I just added an empty function to execute.
