### ISSUE TITLE
Integrate Superfluid Token Streaming for DAIx

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#436]
**DESCRIPTION**

OpenQ now has the capability of minting and indexing fixed-price smart contract bounties from GitHub Issues. This is great for making initial connections with new potential contributors, but many tasks are better suited for salaried on-going relationships.

The cryptonative way to achieve this is via token streaming. Rather than rebuild our own token streaming solution, we've talked with the Superfluid team and believe integrating them might be better.

This task is to create a new page for creating new streams.

**RESOURCES**

I highly suggest following the relevant parts of this tutorial

- [Superfluid JS-SDK: Money Streaming tutorial](https://www.youtube.com/watch?v=fB-YQgwsl0I&t=954s&ab_channel=Superfluid)

0:00 - 05:53: Money Streaming
09:40 - 15:20: Wrapping/Unwrapping Supertokens
15:20 - END: Batch the wrapping and stream creation into one 😀

_Why not just use the Superfluid interface?_ --> Because we intend to add several accounting features on top of the stream which don't exist on Superfluid itself.

**MOCK UP**

The interface can be identical to the one presented in the above tutorial. Just a wireframe really with inputs for addresses.

**ACCEPTANCE CRITERIA**

***User Perspective***

- [ ] I can CREATE, UPDATE and STOP a stream of DAIx from SENDER to RECEIVER at https://localhost:3000/stream
- [ ] Uses the [batch call](https://docs.superfluid.finance/superfluid/developers/interactive-tutorials/batching-transactions) to save on gas and wrap+create in just one transaction
- [ ] Supported tokens: `DAI -> DAIx` (see Wrapping Tokens)
- [ ] Supported networks: `Polygon`
- [ ] I can see in the Superfluid Dashboard that the stream has been established with the proper flow rate and recipient

***Developer Perspective***

- [ ] Uses the existing `useWeb3` hook for connecting to user's wallet (details in **HELPFUL STARTING POINTS** below ;-) )
- [ ] Just console.log the successful output as they do in the tutorial
- [ ] Please create this as a separate service called `SuperfluidClient` in the [services folder](https://github.com/OpenQDev/OpenQ-Frontend/tree/production/services). See other services for examples.
- [ ] Inject the service into our React Context InitialState as we do with our other services [here](https://github.com/OpenQDev/OpenQ-Frontend/blob/production/store/Store/InitialState.js). This is important for mocking and testing purposes.
- [ ] Access the SuperfluidClient on the `appState` as we do with our other services.

[This tutorial](https://youtu.be/q5OcHiSxXfg) will show you how to inject the service.

**WHAT IS NOT IN SCOPE**

- No need to create a token selection component like we have on [Funding](https://app.openq.dev/bounty/I_kwDOGAqhQc5KFb07/0xdc79d3bf0cd11682be000d0001e92b937167c709). You can simply copy+paste the ERC20 token address.

**HELPFUL STARTING POINTS**

- [Next.js /pages where the new page should be added](https://github.com/OpenQDev/OpenQ-Frontend/tree/production/pages)
- [Example of how to access user's eth account with our injectable `useWeb3` hook](https://github.com/OpenQDev/OpenQ-Frontend/blob/4ecabdfc63e5323a168df29812531ab937417cdd/components/WalletConnect/ConnectModal.js#L8)

**Comment by FlacoJones** [comment]
A bounty has been minted for this issue at https://app.openq.dev/bounty/I_kwDOGAqhQc5Lre_g/0xbd9A1864ea59c82913f021c22F0913b0F6A7c249

**Comment by FlacoJones** [comment]
A deposit of  300.0 USD Coin was placed on this issue at https://app.openq.dev/bounty/I_kwDOGAqhQc5Lre_g/0xbd9A1864ea59c82913f021c22F0913b0F6A7c249

**Comment by FlacoJones** [comment]
A bounty has been minted for this issue at https://staging.openq.dev/bounty/I_kwDOGAqhQc5Lre_g/0x58C9a3B43568f07c16D9109685742c517806E275

**Comment by FlacoJones** [comment]
A deposit of  0.01 MATIC was placed on this issue at https://staging.openq.dev/bounty/I_kwDOGAqhQc5Lre_g/0x58C9a3B43568f07c16D9109685742c517806E275

**Comment by jhonnyV-V** [comment]
Hi @FlacoJones , I'm working in a pull request for this issue, but I have a doubt, from this UI, the user should be able to use directly the XDAI in case the user holds the needed amount or should only wrap DAI and create the flow?
