### ISSUE TITLE
Mobile UI: Reposition upper icons on front page

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#472]
Icons look too close to upper end of screen, add space/padding

![image](https://user-images.githubusercontent.com/75732239/176913086-41d86eed-bec5-4800-8a66-89a38c9a9c15.png)

**Comment by FlacoJones** [comment]
A bounty has been minted for this issue at https://staging.openq.dev/bounty/I_kwDOGAqhQc5M-nNq/0xfF62e022Ac37508084732A9Fe69874b40FEfb753
