### ISSUE TITLE
Mobile UI: correct text overlap 

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#474]
Mobile size for which this happens: Samsung Galaxy Fold 
Home page:
![image](https://user-images.githubusercontent.com/75732239/176915879-402e61c7-6cc7-4d59-b538-57f51eef2b02.png)

**Comment by FlacoJones** [comment]
A bounty has been minted for this issue at https://staging.openq.dev/bounty/I_kwDOGAqhQc5M-qpj/0x0533174f05FdCd71C75E9397c96D55E98bF07255

**Comment by Christopher-Stevers** [comment]
I noticed the contract warning at the bottom has been removed, I'm closing this as unneeded.
