### ISSUE TITLE
Mobile UI: add border to issues 

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#475]
Currently there is only a bar separating issues on mobile view:

![image](https://user-images.githubusercontent.com/75732239/176917504-ad9da6a0-a5d3-49c8-9df8-c0c5e91954e8.png)

It would look more organized with a border similar to the desktop view like so:

![image](https://user-images.githubusercontent.com/75732239/176917685-3aeab689-004a-4b30-84da-aba1f1d7956a.png)

**Comment by Christopher-Stevers** [comment]
Hmm, not sure about this one, what do you think @alo9507 . I thought it wasn't bad without the border, because it can feel a little cramped with one.

**Comment by Christopher-Stevers** [comment]
A bounty has been minted for this issue at http://localhost:3000/bounty/I_kwDOGAqhQc5M-s4T/0x8dAF17A20c9DBA35f005b6324F493785D239719d

**Comment by Christopher-Stevers** [comment]
A bounty has been minted for this issue at http://localhost:3000/bounty/I_kwDOGAqhQc5M-s4T/0x8dAF17A20c9DBA35f005b6324F493785D239719d

**Comment by Christopher-Stevers** [comment]
A bounty has been minted for this issue at http://localhost:3000/bounty/I_kwDOGAqhQc5M-s4T/0x8dAF17A20c9DBA35f005b6324F493785D239719d

**Comment by Christopher-Stevers** [comment]
A bounty has been minted for this issue at http://localhost:3000/bounty/I_kwDOGAqhQc5M-s4T/0x8dAF17A20c9DBA35f005b6324F493785D239719d

**Comment by Christopher-Stevers** [comment]
A bounty has been minted for this issue at http://localhost:3000/bounty/I_kwDOGAqhQc5M-s4T/0x8dAF17A20c9DBA35f005b6324F493785D239719d

**Comment by Christopher-Stevers** [comment]
A bounty has been minted for this issue at http://localhost:3000/bounty/I_kwDOGAqhQc5M-s4T/0x8dAF17A20c9DBA35f005b6324F493785D239719d

**Comment by Christopher-Stevers** [comment]
A bounty has been minted for this issue at http://localhost:3000/bounty/I_kwDOGAqhQc5M-s4T/0x8dAF17A20c9DBA35f005b6324F493785D239719d

**Comment by Christopher-Stevers** [comment]
A bounty has been minted for this issue at http://localhost:3000/bounty/I_kwDOGAqhQc5M-s4T/0x8dAF17A20c9DBA35f005b6324F493785D239719d
