### ISSUE TITLE
Mobile UI: Improve "About" page

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#480]
Suggestions to improve the "About" page design:
- Add a border around the About information like on the Desktop view
- Maybe arrange so that the text at the bottom is always in full sight with no need for scrolling
- Maybe put the "Bounties" and "Contributors" information side by side
- Maybe try out centering the about information?

![image](https://user-images.githubusercontent.com/75732239/177092571-a57c8774-8ed7-405d-b648-953eb81727b0.png)

**Comment by Christopher-Stevers** [comment]
@alo9507  what do you think about a border here? We had one in the past that we removed.

**Comment by Christopher-Stevers** [comment]
A bounty has been minted for this issue at http://localhost:3000/bounty/I_kwDOGAqhQc5NDNst/0x8dAF17A20c9DBA35f005b6324F493785D239719d

**Comment by Christopher-Stevers** [comment]
A bounty has been minted for this issue at http://localhost:3000/bounty/I_kwDOGAqhQc5NDNst/0x8dAF17A20c9DBA35f005b6324F493785D239719d
