### ISSUE TITLE
Detect pre-approval amount for ERC20 funding

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#488]
I recently wrapped tokens on Superfluid, and when i was approving something went wrong and I had to reload the page after the transaction had already been mined.

Instead of making me reapprove the same amount, it detected id already approved the amount i was trying to wrap.

Let's do the same for funding, i.e. detect when the user has already approved an amount. If so, they can go right to fund.

**Comment by Christopher-Stevers** [comment]
Not getting anywhere with this one, it keeps returning zero. Let me know if I have any of the numbers wrong here:
```js
const _tokenAddress = "0x5FbDB2315678afecb367f032d93F642f64180aa3"
const funder ="0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
const openQProxy = "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707"
const contract = this.ERC20(_tokenAddress, signer);
const allowance = await contract.allowance(funder, openQProxy);
```

**Comment by Christopher-Stevers** [comment]
@FlacoJones  I'm going to let this one go until I'm running the targeting staging boot. It doesn't seem to be working locally.
