### ISSUE TITLE
Watch Bounty Icon doesn't work if wallet is disconnected

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#491]
We'd like to show it no matter what, and if they click but wallet is disconnected, prompt them to connect then sign the message.

**Comment by Christopher-Stevers** [comment]
A bounty has been minted for this issue at http://localhost:3000/bounty/I_kwDOGAqhQc5NmyIx/0x8dAF17A20c9DBA35f005b6324F493785D239719d

**Comment by Christopher-Stevers** [comment]
A bounty has been minted for this issue at http://localhost:3000/bounty/I_kwDOGAqhQc5NmyIx/0x8dAF17A20c9DBA35f005b6324F493785D239719d

**Comment by Christopher-Stevers** [comment]
A bounty has been minted for this issue at http://localhost:3000/bounty/I_kwDOGAqhQc5NmyIx/0x8dAF17A20c9DBA35f005b6324F493785D239719d

**Comment by Christopher-Stevers** [comment]
A bounty has been minted for this issue at http://localhost:3000/bounty/I_kwDOGAqhQc5NmyIx/0x8dAF17A20c9DBA35f005b6324F493785D239719d

**Comment by Christopher-Stevers** [comment]
A bounty has been minted for this issue at http://localhost:3000/bounty/I_kwDOGAqhQc5NmyIx/0x8dAF17A20c9DBA35f005b6324F493785D239719d

**Comment by Christopher-Stevers** [comment]
A bounty has been minted for this issue at http://localhost:3000/bounty/I_kwDOGAqhQc5NmyIx/0x8dAF17A20c9DBA35f005b6324F493785D239719d

**Comment by Christopher-Stevers** [comment]
A bounty has been minted for this issue at http://localhost:3000/bounty/I_kwDOGAqhQc5NmyIx/0x8dAF17A20c9DBA35f005b6324F493785D239719d

**Comment by Christopher-Stevers** [comment]
> We'd like to show it no matter what, and if they click but wallet is disconnected, prompt them to connect then sign the message.

@FlacoJones  do you want it to directly bring up metamask, pop up the connect wallet modal?
