### ISSUE TITLE
[Re-design] Fix Main Navbar & Make it Responsive

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Frontend#497]
**Description**

From now one main navigation will be from a top Navbar. Fix Links, Logo href "/", Atomic Contracts should be also the first page for now and stay ("/")

Connect Wallet & GitHub Login Buttons need to follow GitHub Style Guide. Search Menu should filter for Organisations or Issues. 

Contest, Communities & Explore isn't needed right now, however, I would actually leave it with 20% opacity and add a coming soon tooltip.

**Comment by ArcAnya** [comment]
WIP

**Comment by ArcAnya** [comment]
Search Menu:  
- I find it might be confusing to be under "organizations" but be able to search for issues as well?..
- ...but if so - I'm assuming it would only be the "organizations" searchbar that should search for both orgs & issues?
