### ISSUE TITLE
[Re-design] Mint Bounty Modal

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Frontend#509]
**Description**

- apply general style guidelines to modal
- add more width to desktop query
- exchange title wording from Mint Bounty to Deploy Contract
- exchange subtitle wording to create an atomic contract to send funds to any GitHub issue
- don't forget to apply same border-radius to modal as the bountyCardModal (sm)

**Comment by ArcAnya** [comment]
WIP
