### ISSUE TITLE
[Re-design] Fund page, Select Token

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Frontend#510]
**Description**

*Fund Page*

- apply Github style guidelines (border-radius, button, tooltip)
- change "Fund Bounty" title to "Fund Atomic Contract" @alo9507 @Christopher-Stevers @ArcAnya  maybe any other wording you would suggest? Maybe lock funds in Atomic Contract or Escrow money?

*Select Token*

- apply Github style guidelines (border-radius, button)

**Comment by ArcAnya** [comment]
WIP
