### ISSUE TITLE
[Re-design] Org Page

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Frontend#520]
**Description**

Take a look at our GitHub org page to get some inspiration: https://github.com/OpenQDev

I think it makes sense to highlight repos that have bounties on the org page and add more granularity to get a better overview before searching for issues.

- Take a look at what we can get from the API, org description, socials, etc and just 1o1 copy the style from Github
- Add a submenu: Overview, About (suggestions for others or renaming may be about to something else? 

**Left**
- Pinned in our case would be active repos that have bounties, if you click on one of these repos it will open a new dedicated page just with the funded issues in that repo with a link tree similar to GitHubs (@Christopher-Stevers  worked on it already in the dedicated bounty page)
- Repository search on GitHub would be our issue search with the same filtering and search mechanisms we added recently

**Right**

- People info same as Github
- Top languages
- Most used topics are not needed right now however check the API for now and get an idea of how the topic system works with Github and get back to me so we can integrate it in OpenQ

**Comment by Christopher-Stevers** [comment]
@rickkdev  I don't believe separate repo specific pages would work well, as we can't get bounties from the subgraph by repo. Theoretically we could get all the issues in the repo from github and then query the subgraph for those issues, or get all bountied issues in the organization from the subgraph and query github for those but that  1) wouldn't be very performant. 2) would likely require some tricky reworking of the pagination system.
So its doable, but not very workable. Could we just stick with them being not clickable, or sending the user to the actual github repository for now?
