### ISSUE TITLE
[Re-design] Contributor Profile

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Frontend#521]
**Description**

Re-design based on inspiration of the Github profile page

- Submenu, Overview, Stars (Orgs), Watching (Issues)

**Overview**
- We just need what we already have on OpenQ, just remove borders and adjust text and size by following the style guidelines

**Stars**
- Display all the Organisations the user followed

*Watching**
- Display all the issues the user followed
- Add some filtering to check which of those issues are closed or still open

**Comment by ArcAnya** [comment]
WIP
