### ISSUE TITLE
When I mint a new bounty it immediately says "Claimed"

### ISSUE THREAD

**Issue by ghost** [OpenQDev/OpenQ-Frontend#550]
<img width="1222" alt="Screen Shot 2022-08-05 at 3 35 49 PM" src="https://user-images.githubusercontent.com/32375569/183088693-c0761e82-888b-496a-9893-d9fe75c2e6b6.png">

**Comment by Christopher-Stevers** [comment]
@alo9507  I can't reproduce this one locally.
