### ISSUE TITLE
Fix rounding on deposit card on timeline

### ISSUE THREAD

**Issue by ghost** [OpenQDev/OpenQ-Frontend#553]
not sure how to do so with things like WBTC where you want like 6 decimal places...but for stables, we only want $0.00 format

<img width="684" alt="Screen Shot 2022-08-05 at 3 55 41 PM" src="https://user-images.githubusercontent.com/32375569/183092051-c2e8df21-b63b-40b9-9339-72d55ddd8ea4.png">

**Comment by Christopher-Stevers** [comment]
@alo9507  We could just set it so that certain addresses round to a higher number. Aren't users going to be funding with reasonable numbers of decimal places on there USDC? Right now if they fund 3.2 USDC it should show 3.2, so the rounding might not be an issue.

**Comment by Christopher-Stevers** [comment]
Will test this out with the targeting-staging environment later, I'm not able to replicate it locally with anything, its possible that it disappeared do to some of the frontend changes.
