### ISSUE TITLE
Add Closed competition + ongoing bounty closed times to the Bounty Timeline

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#560]

**Comment by FlacoJones** [comment]
added the claim time

closed competition and closed bounty can be found on `bounty.bountyClosedTime`

**Comment by Christopher-Stevers** [comment]
I'm not able to make claims on the tiered bounty, openq-oz-autotask fails: [#4](https://github.com/OpenQDev/OpenQ-OZ-Claim-Autotask/issues/4 )
