### ISSUE TITLE
Profile update: Increase profile picture image size & discuss profile picture features

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Frontend#577]
**Description**

We should increase the profile picture size (jazz icon) to the same size on GitHub. That way the sub-menu will be placed in the correct position and is matching style guidelines. 

Meanwhile, we should discuss in this issue and how we want to deal with profile pictures in the future. I think it would be cool if we fetch the GitHub profile picture of users by default if they at least claimed one bounty (that way we know what their Github handle is and can share it publicly via the profile picture)

At the same time, we should allow users to connect an NFT maybe to their profile picture or any other random one?

**Comment by Christopher-Stevers** [comment]
Connecting their Github profile picture sounds like a good idea. If we allow user to connect their own profile pictures then do we need to worry about banning users over their profile pictures?
