### ISSUE TITLE
Dedicated Org Page Active Repositories

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Frontend#584]
**Description**

Currently, if you click on active repositories on a specific organization page, you will be directed to GitHub. In that case, how about creating a new dedicated repository page that shows all contract types for that repository only (also with filter option to look for a specific contract type ? Makes sense to me if I'm only interested in frontend contracts, for example. 

What do you think @alo9507 @Christopher-Stevers @ArcAnya  ?

**Comment by ArcAnya** [comment]
Would be a great value add in my opinion - as a general rule I think it's best to keep the user as much as possible on OpenQ, which of course in this case is best done by providing great search/filter/info options, which add something more than GitHub itself.

**Comment by Christopher-Stevers** [comment]
@rickkdev  I agree it would be a nice feature, however it wouldn't be very feasible at this point. We would need to link the repository address to the bounties in the subgraph and the api. Right now there is no way to, for example fetch all the bounties that are in a certain repository.
Of course its possible to get all the bounties associated with the organization and then just filter them for the page what do you think @alo9507 ?

**Comment by FlacoJones** [comment]
NOTE: using the OpenQ-Token-Price-CronJob we can link the repo to issueId/Org on creation
