### ISSUE TITLE
Linking User Profile 

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Frontend#585]
**Description**

We should link the user profile in the dedicated bounty page

![link user](https://user-images.githubusercontent.com/28826387/184234125-e0b68706-057d-41a3-9c1a-d3c0a3d3901b.png)

**Comment by Christopher-Stevers** [comment]
@rickkdev  do you still want separate profiles for funders and freelancers? If so, we can link the funders for mint/fund and the freelancers for claim.
