### ISSUE TITLE
New Contract button customized per page

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#598]
The "new contract" button should be set to the specific type of bounty when coming from a specific page (atomic, contest...).
Currently it is always set on "Repeating". 

Maybe the submenu (for navigation between the contract types on the MintModal) should also be removed to prevent confusion here? I believe it only makes sense to keep it on the "organizations" view or any other more general view that might include all types.

**Comment by Christopher-Stevers** [comment]
@rickkdev  what do you want the "new contract" button on the dedicated pages for a contract to pop up?
