### ISSUE TITLE
if the budget = 0, the tooltip "question mark" is displayed and says that no budget has been set for this contract

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Frontend#620]
if the budget = 0, the tooltip "question mark" is displayed and says that no budget has been set for this contract

**Comment by ArcAnya** [comment]
Assuming you mean in this location @rickkdev ? 

![image](https://user-images.githubusercontent.com/75732239/185630603-4beac653-8830-4039-b8f5-77dfb6163228.png)

**Comment by ArcAnya** [comment]
Changed it so it now looks like so - lmk if that's not exactly what you had in mind

![image](https://user-images.githubusercontent.com/75732239/185645667-c1674eff-e520-4cba-86ea-19eee019e20a.png)
