### ISSUE TITLE
authState.login undefined

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#653]
It seems like the authState data regarding the login remains undefined even when authenticated with GitHub.
I see it impacting the getBountyMarker logic but maybe it also impacts other logic throughout the app.

![image](https://user-images.githubusercontent.com/75732239/186363960-9034b33d-3763-4dc4-b8de-cb5dcc88094d.png)

**Comment by Christopher-Stevers** [comment]
@ArcAnya  do you have this commit: https://github.com/OpenQDev/OpenQ-Github-OAuth-Server/commit/b3e3608cb8bffade0ad760c5dd97e9965beed032?

**Comment by ArcAnya** [comment]
@Christopher-Stevers actually I do, yes. I just deleted the image and restarted to make sure but still the same. Does it work for you? I'm console logging in BountyHeading.js:

		{console.log(bounty.prs[0].source.author.login)}
		{console.log(authState.login)}
