### ISSUE TITLE
Login Logout from GitHub

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#656]
When I logout of GitHub and decided to login again, it automatically logs in without asking to select a GitHub account / approve. 
(made it more difficult to test claims from other GitHub accounts)

**Comment by Christopher-Stevers** [comment]
I think this is the expected behaviour due to how github handles the oauth, I've noticed its a pain when trying to test claims from multiple accounts as well. @alo9507  can this be closed?

**Comment by ArcAnya** [comment]
Agreed actually, looked into other apps (e.g. Freecodecamp) and they do the same... I'll just close it, if we ever here from users we could think about what can be done.
