### ISSUE TITLE
Improve Message when insufficient funds for claim

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#662]
When I have 0 funds or funds < to reward split amount on repeatable contract, I get the following message when I try to claim (see img). Would it be worth improving that message, e.g. "insufficient funds, contact the organization[...]"

![When_no_Funds](https://user-images.githubusercontent.com/75732239/186386017-3db59a19-b41b-48ad-af8c-aa71f4456666.png)

**Comment by Christopher-Stevers** [comment]
Looks like a Oz-Claim-Autotask issue @FlacoJones

**Comment by FlacoJones** [comment]
Yup, working on it

**Comment by FlacoJones** [comment]
https://github.com/OpenQDev/OpenQ-OZ-Claim-Autotask/commit/f5f43599c2f36f2e2e9436d8474c0a30a80db18d
