### ISSUE TITLE
On Claim, add specific instructions for claimer comment

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#665]
Something like:

"Decide the winner by commenting `OpenQ-Tier-[1,2,3]-Winner` on the winning pull request."

**Comment by Christopher-Stevers** [comment]
Do you want something like this:
![image](https://user-images.githubusercontent.com/72156679/186652809-fa591dbd-f650-437a-a6d4-c65e41e8643a.png)
