### ISSUE TITLE
Improved Claim messaging

### ISSUE THREAD

**Issue by Christopher-Stevers** [OpenQDev/OpenQ-Frontend#668]
Original issue, was a mistake from my end, leaving this open due to Anya's comment. Not able to claim empty competitions: we should either be able to make a claim on them, or the error message should be improved.
![image](https://user-images.githubusercontent.com/72156679/186411584-187d318a-efee-4b41-9499-b19fdbc9facd.png)

**Comment by ArcAnya** [comment]
@Christopher-Stevers Can you claim competitions at all? on my end it still doesn't work

**Comment by ArcAnya** [comment]
It might also be good to think about a different sentence than "You are NOT the droid..." because it can be misleading when it's about insufficient funds for instance:

![image](https://user-images.githubusercontent.com/75732239/186627489-6e100413-51ee-4897-ae8e-5a81be936df3.png)

**Comment by Christopher-Stevers** [comment]
I've also realized that users are allowed to make claims even if the comment on their pr is for a tier that doesn't exist. Not sure if they get money from the claim, but its definitely confusing UX.
