### ISSUE TITLE
Extend Deposit button not working

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#674]
Extend Deposit button does not change expiration in the local subgraph

**Comment by Christopher-Stevers** [comment]
I've been finding that after the user attmept sto extend a deposit fund actions aren't showing up in the subgraph either.

**Comment by ArcAnya** [comment]
Still needs merge from related PRs:
https://github.com/OpenQDev/OpenQ-Contracts/pull/77
https://github.com/OpenQDev/OpenQ-Graph/pull/3
