### ISSUE TITLE
Javascript error on claim 0 tier bounty.

### ISSUE THREAD

**Issue by Christopher-Stevers** [OpenQDev/OpenQ-Frontend#693]
Getting this error if I try to set the tier for claim at 0, not sure if its an issue to worry about.
![image](https://user-images.githubusercontent.com/72156679/186740508-46979788-b7ce-4f39-8b07-d8f622fc4836.png)

**Comment by ArcAnya** [comment]
Can you elaborate on the steps you did? Normally tiers should not be 0 I believe, but I'm not sure I understand the issue exactly so lmk.

**Comment by Christopher-Stevers** [comment]
I made a mistake when I claimed the attempted to claim the bounty by commenting openq-winner-0, I'm not sure if this is worth worrying about, because usually users should be commenting something above zero.
