### ISSUE TITLE
User Pages

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#71]

**Comment by Christopher-Stevers** [comment]
@FlacoJones  this will be similar to the about tab on the org  page, right? So right now we'll display total value claimed per user, number of prs, and number organizations contributed too? Unfortunately users can just mint and claim bounties on their own repos, so the first to metrics won't be very trustworthy.

Eventually we could have reputation and reviews.

**Comment by FlacoJones** [comment]
Yeah absolutely to all the above.

Including things like total payouts across different tokens, that kinda stuff as well.

This will start basic and build up more and more.
