### ISSUE TITLE
Improvements for contract description 

### ISSUE THREAD

**Issue by Sixto5** [OpenQDev/OpenQ-Frontend#737]
Suggestions: 

- change 'Type' into: 'Type of contract'.
- TVL into: Total Value Locked
- Label into: Github Label 
- Ideation about signalling the time frame of the issue. For example shows: days - weeks - month 
@rickkdev @FlacoJones what do you think? 

![image](https://user-images.githubusercontent.com/44020385/191528055-d39617bd-b1b9-4af4-a3f6-59ba39c628f8.png)

**Comment by ArcAnya** [comment]
For the last point about ideation cf my comment here: https://github.com/OpenQDev/OpenQ-Frontend/issues/742#issuecomment-1254663147
