### ISSUE TITLE
Address / ENS confusion

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#751]
On staging: I'm assuming the shown address/jazzicon is all from flacojones. If so, I guess it should always show flacojones, and the "double" jazzicon on the first minted actionbubble should be fixed.

![image](https://user-images.githubusercontent.com/75732239/191692774-181209cd-e1b8-44cd-a4ed-67884f1b54b6.png)

**Comment by FlacoJones** [comment]
ya if ENS is available we only want to show the ENS

**Comment by Christopher-Stevers** [comment]
@ArcAnya  the second jazzicon looks like flacojones.eth, and I'm pretty sure the address 0x46...624b is his, but the black and jazzicon is mine - 0xa7b7DcBb35A58294Ba9E51cC9AA20670E124536b 
I'd guess what happened here is that he minted and  I funded, but my address isn't showing up on the funding.
If you have an ens address could you debug this one? I don't have one yet, so its a bit of a pain to figure it out on my end.

**Comment by ArcAnya** [comment]
I just saw - I guess the issue is the same or related to #735 
I don't have an ENS one yet either so far. Let's see whether it's priority - I can look into getting an ENS address

**Comment by ArcAnya** [comment]
@Christopher-Stevers do you think it is related to #756 and #735 - looks like it might all be the same to me, and potentially not related to ENS?

**Comment by Christopher-Stevers** [comment]
Looks like it @ArcAnya
