### ISSUE TITLE
Weird thing showing double minters?

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#756]
https://app.openq.dev/bounty/I_kwDOHB1JPc5L_866/0xa696f455dfe75cca92e8afd7f14c1bb5768f4bf6

0x46 is me but i didn't mint this Honey bounty. i test funded it

**Comment by ArcAnya** [comment]
Might be related to #735 and #751?

**Comment by Christopher-Stevers** [comment]
> Might be related to #735 and #751?

It is.
