### ISSUE TITLE
Split-price: only one tokenAddress for payout vs. many deposits possible

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#759]
For a split-price contract, currently it is possible to fund deposits for multiple different tokens, but the payout will always be set to only one specific token.

Would be nice to either:
- (1) fix the possibility to fund deposits to only the payout tokenAddress
- OR (2) make it possible to have a multiple token payout 

@rickkdev @alo9507 what do you think?

**Comment by FlacoJones** [comment]
Let's go with Option 1
