### ISSUE TITLE
Adding In-depth analytics

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Frontend#771]
**Details/ Requirements:**

To successfully onboard organizations and developers in the coming months, we need good analytical tools to track users.

It is important to be able to see general user behavior. How many use the app, how many go from the landing page to the app, and which areas of the app are used how often.

Furthermore, we need a powerful tool to onbaord new users. For this, it is important to recognize whether users we invite (via a link created especially for them) are clicking the link and becoming active users afterwards.
This is especially interesting because we have different strategies for onboarding and want to see what works and what does not.

An interesting tool for this seems to be Livesession, but maybe someone knows something better or has experience with other tools:

Here is the website:
https://livesession.io/pricing/

**What do we need?:**

We should start with Google Analytics & play around with Hotjar:

**_Google Analytics:_**
- How many people are using the app & landing page
- How many people have seen a fixed-price, split-price or contest issue, best would be how many have checked the modal, how many the dedicated page and how many just browsed through the issue and had their mouse pointed to it (that's where hotjar gets interesting)

**_Hotjar_**
- For now just add it to the app and landing page and we see from there how we want to adjust it. Main idea is to see how many people stop scrolling the page for a specific issue

_**Live Session Feature**_
- We need to be able to generate links for specific strategies we are playing around with and want to see if this strategy is successful
- Check out life session docs and see if it fits the explained requirements above. It should work for the landing page and application meaning if we track a link to the landing page we should also see if people afterwards check out the app and long-term become an active user

**Comment by ArcAnya** [comment]
Regarding Live Session - tracking new users' behavior via link invites seems possible: https://developers.livesession.io/javascript-api/tutorials/#tracking-users-across-multiple-subdomains
![image](https://user-images.githubusercontent.com/75732239/192496186-e4e1f2b9-e37b-4c40-9337-2e2476c582c8.png)
