### ISSUE TITLE
[ATOMIC CONTRACT]: Add a Lock icon next to TVL and target icon next to budget

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#774]
### 📃 Description

Real quick. Just add these emojis to TVL and Current Target Budget parts of OpenQ

### 👨‍⚖️ Acceptance Criteria

It matches the attached screenshot

### 💰 Budget

$10 USDC

### 🖼 Screenshots + Mock Ups

<img width="368" alt="Screen Shot 2022-09-27 at 1 34 24 PM" src="https://user-images.githubusercontent.com/93455288/192596801-d19bb300-84ee-47f5-8851-dd1e676817b1.png">

### 🎬 Where to Start

[BountyMetadata.js](https://github.com/OpenQDev/OpenQ-Frontend/blob/staging/components/Bounty/BountyMetadata.js)

**Comment by Vinitvh** [comment]
Hi, I would like to add these.

**Comment by FlacoJones** [comment]
Hey! sounds good to me. let me assign you

**Comment by FlacoJones** [comment]
@Vinitvh you are now assigned: https://app.openq.dev/bounty/I_kwDOGAqhQc5SvSU7/0x7b0c65da30401d2e45d98440ac158add3aa89698

Make a PR that references this issue (Closes #774) from your fork, and then you'll be able to claim once I review and merge. Just deposited the 10 USDC
