### ISSUE TITLE
Fix APP UI: BountyCard & Dedicated Bounty Page

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Frontend#775]
- Budget is currently not really noticeable if there is no TVL, we should show it as a placeholder for TVL in the upper right corner.
- The new contract button and github icon is placed incorrectly. It should be on the same height as the title and have some padding between the text like 20 or so

![app design adjustments](https://user-images.githubusercontent.com/28826387/192630201-382659b8-b4fc-4369-aa78-cf8a78eb9473.png)

- for some reason the budget breaks a column in the bounty card, check main prod page for reference: 
https://app.openq.dev/organization/OpenQDev
![what](https://user-images.githubusercontent.com/28826387/192629993-393aadd4-efa3-4993-99f3-d12cac6fc980.png)

**Comment by ArcAnya** [comment]
Cf commits: 
https://github.com/OpenQDev/OpenQ-Frontend/commit/426c0479ef8279a0e3434ff9875e11ada93947ae
https://github.com/OpenQDev/OpenQ-Frontend/commit/8058fd18c869ddaa32033ed4412f148707c1fb49
https://github.com/OpenQDev/OpenQ-Frontend/commit/bf701b817787ee323fe34c9421c3474d82549290
