### ISSUE TITLE
Starred orgs not showing on User Page

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#784]
<img width="1134" alt="Screen Shot 2022-10-02 at 2 44 24 PM" src="https://user-images.githubusercontent.com/93455288/193470713-7efc4b22-1a12-434b-a239-81f85168975a.png">
<img width="1128" alt="Screen Shot 2022-10-02 at 2 44 30 PM" src="https://user-images.githubusercontent.com/93455288/193470715-c8c01c5d-ac3f-4b0f-b262-b4ba50c1bf2a.png">

**Comment by Christopher-Stevers** [comment]
@FlacoJones  have you tried starring something? It's working on prod on my end if I've starred something because then the signature cookie has been set. Do you think we should have users sign the signature when they connect their wallet? I've definitely seen it done in a dApp before.

**Comment by FlacoJones** [comment]
aha, i bet its the missing signature then. hm, let me return to this later since im working on SIWE today anyways
