### ISSUE TITLE
Footer redesign

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#787]
Ngl our Footer has fallen by the wayside (except for our smart contract pop-up which is dope).

I like this style:

<img width="1400" alt="Screen Shot 2022-10-02 at 6 48 36 PM" src="https://user-images.githubusercontent.com/93455288/193479781-9883d549-e0eb-4ef8-bf7d-8391bcff7e97.png">

Minus the newsletter thing

**Comment by Christopher-Stevers** [comment]
@FlacoJones  like this and the same colour as rest of the background then? Mocked it up in figma since the content is a bit different.than 101's
![image](https://user-images.githubusercontent.com/72156679/193558002-c3bc4d38-b28b-43a7-800c-f8c83e0d9296.png)

**Comment by FlacoJones** [comment]
yup, perfect

**Comment by FlacoJones** [comment]
minus the careers and roadmap since wr honestly dont really have a public facing site for those (yet)
