### ISSUE TITLE
Footer fixes

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#793]
3 bugs i see on staging:

- The Feature request thing links to staging url but should be https://openq.canny.io/openq-feature-requests
- Documentation should link to docs.openq.dev
- The contract addresses overlap weirdly, screenshot:

<img width="270" alt="Screen Shot 2022-10-03 at 7 12 50 PM" src="https://user-images.githubusercontent.com/93455288/193702206-558ffda0-6236-4987-aa7c-9e1b7d768d50.png">

**Comment by ArcAnya** [comment]
The contract addresses overlap also happens on mobile-view (double-check that it works properly there as well):
![image](https://user-images.githubusercontent.com/75732239/193788687-086d77e0-4011-44ce-b62e-00b6d0ad87c9.png)
