### ISSUE TITLE
[Mobile UI] Label list cut

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#797]
When adding labels to search, when the field is too small for all the labels, it doesn't show the latest addition(s)
I suggest to either wrap the search field to show all search labels etc. OR move the cursor of the field to the end, so that it always shows the latest addition.
![image](https://user-images.githubusercontent.com/75732239/193791250-29617be6-93bd-46c3-a1ef-eda9d81e2cf6.png)

**Comment by Christopher-Stevers** [comment]
@ArcAnya  I looked for a way to manipulate the input focus but didn't see anything and I've noticed the same behaviour on Github, so I'm closing this.
