### ISSUE TITLE
Not eligible to claim any bounty (any contract type)

### ISSUE THREAD

**Issue by VictoQ** [OpenQDev/OpenQ-Frontend#817]
I get several error messages when I try to claim a bounty, even though my PR has been merged and the website itself says an claim is available

![fixed price claim II](https://user-images.githubusercontent.com/100775733/194577789-13a52032-fad0-46ad-9730-1c8f7c21f143.gif)

![claiming contest new](https://user-images.githubusercontent.com/100775733/194577633-1587df4f-6b36-43b8-8aef-efb61ca4a509.gif)

**Comment by Christopher-Stevers** [comment]
@FlacoJones  can you look at this? It looks like an issue with the oracle or claim autotask.

**Comment by ArcAnya** [comment]
[Note: I was unable to reproduce this on staging, with a second GitHub account / wallet]
