### ISSUE TITLE
Connect Wallet on Mobile functionality improvement

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#829]
Just tried staging.openq.dev on my actual mobile phone and ran into the following:
- Brave browser: it suggests to me to connect to the Brave wallet.
- Safari: nothing happens.

How likely is it that someone has the MetaMask extension on their browser on mobile? Should we guide users to click WalletConnect when detecting that there is no extension & they are on mobile? 

![image](https://user-images.githubusercontent.com/75732239/196100072-8a6669f5-d12e-4bbc-a707-0b8003486003.png)

**Comment by ArcAnya** [comment]
Suggest downloading the Metamask App when on Mobile

**Comment by Christopher-Stevers** [comment]
Uniswap looks for brave instead of metamask in a similar situation.  I think that should be good for now.
