### ISSUE TITLE
Why don't we show the Deposits (aka RefundPage info) to all?

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#837]
Trying to look at the deposit period for the EthBerlin Bounty from Pinata on our App, but couldn't find it - only found the date at which it happened.
 
What's the reason for hiding the "RefundPage" deposit overview to other users? Isn't the info on the Blockchain anyways and wouldn't it be good to show transparently what's deposited till when on the contract?

Suggestion: Renaming the RefundPage "Deposits" and making the deposits of the RefundPage visible to all, with actions (refund/extend) obviously only available to funders. For crowdfunding we need to separate the user's deposits from others, we could start by just having a subheader "Your Deposits" vs. "Other Deposits" in each category - and think of something better down the road.

Additionally, I would suggest linking the TVL on BountyCardLean, BountyCardDetailsModal etc. to that deposit overview - to make it easy for the user to see what's going on.

**Comment by Christopher-Stevers** [comment]
Moving this to new issues since we agreed that its a good idea in the meeting.
