### ISSUE TITLE
Error on Gnosis Safe + Wallet Connect

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#840]
The error message received when someone tried to fund with Wallet Connect + Gnosis Safe (unsure in what browser) was simply "reverted without a reason string"

Let's try to go through this again?

Would it be easier if we told people to use a Gnosis App we make? Rather than going through Wallet Connect + Gnosis?

**Comment by Christopher-Stevers** [comment]
@FlacoJones  looks like walletconnect is broken everywhere. Will get it working, then check to make sure it works with gnosis safe
