### ISSUE TITLE
Show "Claimed amount" and merged when contract is claimed, rather than Budget

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#848]
https://app.openq.dev/bounty/I_kwDOHB1JPc5Tux7f/0xe51ed089272f52fe2ca6b3070b4adfb8a0b7c221

Still kind of weird how we show budget even after contract is claimed

<img width="1058" alt="Screen Shot 2022-10-24 at 11 08 04 AM" src="https://user-images.githubusercontent.com/93455288/197573429-3d2f8f44-f1b9-4126-9246-fdf6b73d4532.png">

**Comment by FlacoJones** [comment]
Remove TVL and Budget in the sidebar, just show "Claimed"

This may require API updates as well?

<img width="336" alt="Screen Shot 2022-10-24 at 11 09 06 AM" src="https://user-images.githubusercontent.com/93455288/197573688-dc5ddf30-2918-495f-bbaf-ab3b2514c1b8.png">

**Comment by Christopher-Stevers** [comment]
Yeah, it requires cron job updates.
