### ISSUE TITLE
Funded an issue with the "wrong" Metamask account

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#856]
Logged into Staging with account 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 (from local env) and was able to fund an issue because my actual account (0x4f52d5D407e15c8b936302365cD84011a15284F2) which I had connected to staging in the past was used instead.

I think this should not happen. Suggestion: detecting which account is currently selected in Metamask, an if another one is going to be used the user should at least be shown a confirmation modal for using the other account. Can we do this?

Had a quick look at Uniswap which also seems to automatically connect to previously connected accounts - can we be better than that?

**Comment by Christopher-Stevers** [comment]
Not sure if we can do better than them - useWeb3React is used and maintained by Uniswap.

**Comment by Christopher-Stevers** [comment]
Probably would  be worth a quick check, but I doubt we could do any better than them.

**Comment by ArcAnya** [comment]
Rechecked this issue and it seems to work perfectly fine now - dismissing the issue.
