### ISSUE TITLE
On profile page, watched issues not always showing

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#864]
If I go to my profile and on the Watching tab, at first my watched issues won't show, but once I reload and go on the tab again they will.

![image](https://user-images.githubusercontent.com/75732239/198233529-d02b109f-30fc-45b5-82d2-ea9ee57af69d.png)
![image](https://user-images.githubusercontent.com/75732239/198233609-b94b3b03-ba4f-4219-9970-c6c4dae76872.png)

**Comment by Christopher-Stevers** [comment]
Seeing the same thing here. With authentication changes in the near future I think its worth waiting until those are finalized.
