### ISSUE TITLE
Add the Gnosis Safe heads up text to the Funding modal as well

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#879]
I like the Gnosis Safe App notifier on mint bounty.

Let's add it to the Fund modal as well, since i bet even more often people will be using Safes to fund than to mint

**Comment by Christopher-Stevers** [comment]
@FlacoJones its actually in the connect wallet modal at the moment so we should be catching all users who are doing anything  😃
