### ISSUE TITLE
[Mobile UI] Get rid of border radius on modals at small viewpoint widths.

### ISSUE THREAD

**Issue by Christopher-Stevers** [OpenQDev/OpenQ-Frontend#894]
Border radius at the corner of the modal looks odd when the modal is full width. There should be a breakpoint where the modal goes from being full width with no border radius to being not full width with border radius.

![image](https://user-images.githubusercontent.com/72156679/199084279-b3eb67c1-10a8-4fbb-a80e-8b7d53a1594b.png)

**Comment by ArcAnya** [comment]
Agreed, indeed, it's in the GitHub design guidelines but since I'm not done with all modals yet I haven't had the time to do this yet. 
Should follow this: https://primer.style/design/components/dialog#dialogs-should-work-well-on-any-device
