### ISSUE TITLE
Add a /user/github/githubId

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#896]
- Add a route here in which a user can OAuth as a Github user and associate a wallet address to their Github ID
- Add a prompt, like in ClaimPage, to prompt the user to sign in. Make sure you set this route as the return url for the OAuth flow.
- Add a button for 'Associate Ethereum Address to your Github'
- Add an input to copy/paste the address you would like to associate. No need to sign a message. Not sure why someone would want to send funds to another address? Any hacks here?
- Add a small descriptive text that says “You MUST sign up with Github in order to receive prize payouts in our seasonal hackathons! Funds will be sent to the address you put here. You can change this at any time”
- Perhaps there can be solid code reuse between this and the existing /user page? TBD
- Related to https://github.com/OpenQDev/OpenQ-User-Registration/issues/1. This OZ Defender Autotask will be what is called with a signed OAuth token on clicking 'Associate Ethereum Address to your Github'. This oracle will take care of it

**VERY ROUGH SKETCH**

<img width="717" alt="Screenshot 2022-10-31 at 5 47 35 PM" src="https://user-images.githubusercontent.com/93455288/199124201-9e89d857-878f-4237-bd74-eb57db3ad1c7.png">

NOTE: This will be the Github User Id, not the username/login because people can change those and it migrates their previous changes to the new name (https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-personal-account-settings/changing-your-github-username)

`REQUEST BODY`

```json
{
    'userId': <Github User ID>,
    'userAddress': <The eth address to update to>
}
```

The Github User Id is available on the User object in the Github GraphQL API

**Comment by ArcAnya** [comment]
Regarding the Profile page: I guess if the connected ETH address is different from the one related to the GitHub profile, we should probably differentiate? i.e. Have a "GitHub profile" page and "Ethereum profile" one (and adding a line for each in the relevant modal to get to the profile(s) ). Otherwise we could combine both.

**Comment by Christopher-Stevers** [comment]
NB. only issue left here is the redirects. My apologies if I removed any of the stuff surrounding redirects, in any case it should be accessible in the commit history.
