### ISSUE TITLE
[PROD] Sorting options on homepage need double click

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#899]
(discovered by the streaming community) It seems like we need to double click (instead of one click) to be able to sort / filter the bounties on the homepage:

![image](https://user-images.githubusercontent.com/75732239/199215133-af43b64f-8e00-4444-964a-385ba5fc9e29.png)

**Comment by jhonnyV-V** [comment]
It looks like some how is related to the mousedown event listener, I removed all the mousedown listeners and the dropdown worked with just 1 click
