### ISSUE TITLE
Check the Graph for a null externalUserId on User before allowing tier selection, notify if null

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#903]
After we have the happy path for tier selection working, this is the first thing we should do to save users from themselves.

We should notify in the transaction modal if the user being selected doesn't have an address associated.

This is kind of like how we check the ERC20 balance before funding.

**Comment by FlacoJones** [comment]
If the graphs all wonky which it may be given this is a new (albeit tested) mapping, just call the contract directly and see if it's the zero address

**Comment by Christopher-Stevers** [comment]
I already set it to call the contract directly in #905
