### ISSUE TITLE
Incorporate Total Value Claimed

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#912]
This had $1,000 claimed on it, and this should show prominently instead of TVL when it's been claimed.

If a contract has been claimed, can we toggle this to show "Claimed" instead of TVL? Makes no sense to show TVL as 0 (even though it is since it's been paid out)

<img width="959" alt="Screenshot 2022-11-05 at 4 58 34 PM" src="https://user-images.githubusercontent.com/93455288/200147698-58566973-81b4-46c2-b90e-9fcdde36c5fe.png">

**Comment by Christopher-Stevers** [comment]
Looks like tvc isn't being updated in the api. I'll make it display payoutToken balances at the moment, then once I can access bounty actions autotask.
