### ISSUE TITLE
Authentication System and User Manangement

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Frontend#933]
### 📃 Description

To bring our authentication system and user management to the next level so that we can properly analyze active users and their skills and meet the requirements of hackathon organizations I'm putting together all the specs we need to properly support the Polygon Hackathon from December 16 and make a great return.

The aim is to learn as much as possible from the user during registration or to obtain more information from the user at a later stage.

### 👨‍⚖️ Acceptance Criteria

**Authentication:**

Wallet connect will still be the main identifier, we try to make the UI/UX better to get more informations about the user.

- [x] If User connects with Github we want to see if we can also store their Email and Twitter handle and connect everything we get (github name, email, socials to our database)

**Profile Page**

- [x] In Overview show all socials (with an edit button to add them not in editing see screenshot below), socials we need: Email, Twitter, Github (if Oauthed autofill if multiple github accounts later use the most recent one in frontend but store everything), Discord
- [x] Put Subscribe feature from editing into the overview page at the bottom
- [x] Github and Email should be autofilled in the form if we already have it, if we don't have the Github users should Oauth to get it connected and not just type it (that will give us all the info like email etc which we can autofill in their profile and they are signed up then + we can make sure its their real github)
- [x] "Editing" sub menu should not be called "editing" instead "invoice details" 
- [x] Remove socials input from Editing/ invoice details since its in overview (those can be typed but it should look like this:
![twitter](https://user-images.githubusercontent.com/28826387/200915246-9fccff5a-92b9-4ab0-9c82-102be0fec6ef.png)

the input field should only be visible if you click the edit button otherwise "-" if no data or we display their name with a hyperlink to their profile if you click on the text

- [x] Skills in overview also with an input field where they can add all frameworks, programming languages, and roles (frontend, backend, devops, fullstack)

![skills](https://user-images.githubusercontent.com/28826387/200902523-7285d5e7-debe-44cf-96a8-4fec4fe19c37.png)

All of those changes should give us more informations about the users. 

**Non Dev Skills**

- [x] We should also add non dev skills so maybe aside from the main three skills we should add another one which is called others, where you can enter like figma, adobe, etc, 
- [x] roles:  people can also type biz dev, marketing etc. So we should give them for example frontend, backend, biz dev, ui/ux, and marketing. That will make clear that we are not only looking for dev skills. Should be sufficient to start having more general profiles.

**Bonus**
- [x] Get from the GitHub Account the programming languages the user coded in their open source repos and autofill them in the skills page

**Comment by FlacoJones** [comment]
```
If User connects with Github we want to see if we can also store their Email and Twitter handle and connect everything we get (github name, email, socials to our database)
```

When they OAuth we have the `read:user` scope, so i think we can get this info. You want to automatically "sync" this to our API basically and display it on the /user/profile page?

**Comment by FlacoJones** [comment]
So the enum for roles would be:

Frontend
Backend
Smart Contract
Business Development
UI/UX Design
Marketing

**Comment by Christopher-Stevers** [comment]
- whenever user logs in to GitHub and they connected their wallet store in the database the association 
- remove from nav GitHub login and put that into the profile page 
- if PAt is exhausted redirect to profile page ask ppl to verify account 
- in nav menu if user is not verified (they didn’t connect their GitHub while their wallet is connected) put a little label next to the profile icon and say verification needed 
- in profile page if user didn’t verify yet make a notification at the top and ask user to connect their GitHub account to verify 
- also store the GitHub account with our user if they claim a bounty
The associate GitHub account thing should be then at the beginning of the profile page in a submenu
We need to tell them that that will be stored on chain and if they are not okay with that they should use a different GitHub account
For the contest thing we should tell the users somewhere to be able to receive money they need to associate their account
