### ISSUE TITLE
Submissions not autoupdating.

### ISSUE THREAD

**Issue by Christopher-Stevers** [OpenQDev/OpenQ-Frontend#942]
Submissions not auto updating. Picked a submission and I had to reload to see the claim information update. I also claimed another submissions and it didn't turn gray as I expected it would.

![image](https://user-images.githubusercontent.com/72156679/200932096-0cda2f6f-2533-464e-8d68-bf91e5cb1591.png)

**Comment by FlacoJones** [comment]
I just tried this in staging.

It's a graph problem

**Comment by Christopher-Stevers** [comment]
@FlacoJones  this can be closed right?
