### ISSUE TITLE
Account for user denied OAuth

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#943]
When they deny they're redirected back to here

http://localhost:3000/auth/github?error=access_denied&error_description=The+user+has+denied+your+application+access.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23access-denied&state=%7B%229959zjmfmd%22%3A%7B%22redirectUrl%22%3A%22http%3A%2F%2Flocalhost%3A3000%2F%22%7D%7D

**Comment by ArcAnya** [comment]
Github login still not working locally, but I guess adding something along the lines of:
```
if (router.query?.error == 'access_denied') {
      router.push(redirectUrl);
    }
```
Would go in the right direction?
