### ISSUE TITLE
Show some ribbon SVG on the winner submissions with the place they came in

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#951]

**Comment by FlacoJones** [comment]
Also, remove the ability to select the same PR twice

**Comment by Christopher-Stevers** [comment]
Wasn't sure what to do for ribbon, so I went with this, keeps are colours and use octoicons, so hopefully its good.
Any thoughts @ArcAnya ?
![image](https://user-images.githubusercontent.com/72156679/201100322-2ddc5313-6319-4307-96ac-aca71fcae831.png)

**Comment by ArcAnya** [comment]
I think it looks pretty good for now, definitely clean <3
The only thing is I would maybe also change the background from the whole card for winners so that they stick out even more (maybe some gray or so?)

**Comment by Christopher-Stevers** [comment]
Sounds, good, I'll lighten it up a bit.
