### ISSUE TITLE
Fix: Cup showing when modal on

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#966]
![image](https://user-images.githubusercontent.com/75732239/201159159-25602eb3-ce09-418c-92d7-da530ff68c9b.png)

**Comment by Christopher-Stevers** [comment]
Cup is also showing up too low as well:
![image](https://user-images.githubusercontent.com/72156679/201161455-a49dfbc5-4e1c-4245-8d8d-786742b93e88.png)
