### ISSUE TITLE
Hackathon Submission Page Bug

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Frontend#985]
Page is currently not loading in staging;
https://staging.openq.dev/organization/ethbrno 
![image](https://user-images.githubusercontent.com/28826387/201695724-95892733-9a2a-416d-b156-3665ce418e35.png)

**Comment by ArcAnya** [comment]
Was it because there were no submissions?
I see this now:

![image](https://user-images.githubusercontent.com/75732239/201698510-c0172248-b62d-4229-bac4-092b0c849bd0.png)

**Comment by Christopher-Stevers** [comment]
@ArcAnya no, actually it was looking for a bounty connected to the prs but not finding them. I introduced it, but it never got push to prod, I've pushed a fix to staging.openq.dev, and it'll be a part of my next pr.
