### ISSUE TITLE
Normalize Ready for Work Criteria for each type

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#990]
Refactoring the BountyList if/then spaghetti

**Comment by ArcAnya** [comment]
I tried to restructure the conditional logic in condition "chunks" and added comments to clarify (PR #992). Is that enough? Did we want to change any condition?
Specific commit: https://github.com/OpenQDev/OpenQ-Frontend/pull/992/commits/b631dec19f12b75743005b7ca7cdeb3362f34e75

@Christopher-Stevers feel free to let me know your thoughts as well

**Comment by Christopher-Stevers** [comment]
That commit looks good to me, as long as the filtering function is taken out of bountylist, it should be good to go.

**Comment by ArcAnya** [comment]
Yes, I've extracted it in a separate file: https://github.com/OpenQDev/OpenQ-Frontend/pull/992/commits/6ea5c205c620485a5e0c21db8b364a415f064e10
