### ISSUE TITLE
Hackathon Submissions Cleanup

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Frontend#993]
![submissions-2](https://user-images.githubusercontent.com/28826387/202219392-597164c5-e907-45fb-a608-65c333ae5319.png)
https://app.openq.dev/organization/OpenQDev

1. Even though there are 362 submissions only two cards are showing up and their CSS is messed up they should be on the left side

2. If we mint within a repo that we use for testing a contest bounty PRs of all kind also for issues that are not contests are shown. We should have a blacklisting method for these to be able to curate submissions.

**Comment by Christopher-Stevers** [comment]
enable pagination - currently we are just fetching the first 100.

**Comment by Christopher-Stevers** [comment]
@alo9507  for blacklisting submissions can we use the unused pr model that's currently in the API? When organizers want to blacklist a submission we'd add it to the api with blacklisted as true. Then on the submissions page we could fetch all prs with blacklist of true and prevent them from being displayed. Also, we should probably add blacklist functionality to the repositories so if users create a contest in a repository that's not made for contests they will be able to blacklist the repository and have submissions from that repository hidden in the frontend.

**Comment by FlacoJones** [comment]
Ya that sounds like a good idea. go for it
